 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, change the source JSONSchema file,
 * and run generate-woocommerce-types.js to regenerate this file.
 */

export interface ProductCat {
  /**
   * Unique identifier for the resource.
   */
  id?: number;
  /**
   * Category name.
   */
  name?: string;
  /**
   * An alphanumeric identifier for the resource unique to its type.
   */
  slug?: string;
  /**
   * The ID for the parent of the resource.
   */
  parent?: number;
  /**
   * HTML description of the resource.
   */
  description?: string;
  /**
   * Category archive display type.
   */
  display?: 'default' | 'products' | 'subcategories' | 'both';
  /**
   * Image data.
   */
  image?: {
    /**
     * Image ID.
     */
    id?: number;
    /**
     * The date the image was created, in the site's timezone.
     */
    date_created?: {
      [k: string]: unknown;
    };
    /**
     * The date the image was created, as GMT.
     */
    date_created_gmt?: {
      [k: string]: unknown;
    };
    /**
     * The date the image was last modified, in the site's timezone.
     */
    date_modified?: {
      [k: string]: unknown;
    };
    /**
     * The date the image was last modified, as GMT.
     */
    date_modified_gmt?: {
      [k: string]: unknown;
    };
    /**
     * Image URL.
     */
    src?: string;
    /**
     * Image name.
     */
    name?: string;
    /**
     * Image alternative text.
     */
    alt?: string;
    [k: string]: unknown;
  };
  /**
   * Menu order, used to custom sort the resource.
   */
  menu_order?: number;
  /**
   * Number of published products for the resource.
   */
  count?: number;
  [k: string]: unknown;
}
