 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, change the source JSONSchema file,
 * and run generate-woocommerce-types.js to regenerate this file.
 */

export interface Customer {
  /**
   * Unique identifier for the resource.
   */
  id?: number;
  /**
   * The date the customer was created, in the site's timezone.
   */
  date_created?: {
    [k: string]: unknown;
  };
  /**
   * The date the customer was created, as GMT.
   */
  date_created_gmt?: {
    [k: string]: unknown;
  };
  /**
   * The date the customer was last modified, in the site's timezone.
   */
  date_modified?: {
    [k: string]: unknown;
  };
  /**
   * The date the customer was last modified, as GMT.
   */
  date_modified_gmt?: {
    [k: string]: unknown;
  };
  /**
   * The email address for the customer.
   */
  email?: string;
  /**
   * Customer first name.
   */
  first_name?: string;
  /**
   * Customer last name.
   */
  last_name?: string;
  /**
   * Customer role.
   */
  role?: string;
  /**
   * Customer login name.
   */
  username?: string;
  /**
   * Customer password.
   */
  password?: string;
  /**
   * List of billing address data.
   */
  billing?: {
    /**
     * First name.
     */
    first_name?: string;
    /**
     * Last name.
     */
    last_name?: string;
    /**
     * Company name.
     */
    company?: string;
    /**
     * Address line 1
     */
    address_1?: string;
    /**
     * Address line 2
     */
    address_2?: string;
    /**
     * City name.
     */
    city?: string;
    /**
     * ISO code or name of the county, state, province or district.
     */
    state?: string;
    /**
     * Postal code.
     */
    postcode?: string;
    /**
     * ISO code of the country.
     */
    country?: string;
    /**
     * Email address.
     */
    email?: string;
    /**
     * Phone number.
     */
    phone?: string;
    [k: string]: unknown;
  };
  /**
   * List of shipping address data.
   */
  shipping?: {
    /**
     * First name.
     */
    first_name?: string;
    /**
     * Last name.
     */
    last_name?: string;
    /**
     * Company name.
     */
    company?: string;
    /**
     * Address line 1
     */
    address_1?: string;
    /**
     * Address line 2
     */
    address_2?: string;
    /**
     * City name.
     */
    city?: string;
    /**
     * ISO code or name of the county, state, province or district.
     */
    state?: string;
    /**
     * Postal code.
     */
    postcode?: string;
    /**
     * ISO code of the country.
     */
    country?: string;
    /**
     * Phone number.
     */
    phone?: string;
    [k: string]: unknown;
  };
  /**
   * Is the customer a paying customer?
   */
  is_paying_customer?: {
    [k: string]: unknown;
  };
  /**
   * Avatar URL.
   */
  avatar_url?: string;
  /**
   * Meta data.
   */
  meta_data?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
