 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, change the source JSONSchema file,
 * and run generate-woocommerce-types.js to regenerate this file.
 */

export interface ShopOrder {
  /**
   * Unique identifier for the resource.
   */
  id?: number;
  /**
   * Parent order ID.
   */
  parent_id?: number;
  /**
   * Order number.
   */
  number?: string;
  /**
   * Order key.
   */
  order_key?: string;
  /**
   * Shows where the order was created.
   */
  created_via?: string;
  /**
   * Version of WooCommerce which last updated the order.
   */
  version?: string;
  /**
   * Order status.
   */
  status?:
    | 'auto-draft'
    | 'pending'
    | 'processing'
    | 'on-hold'
    | 'packed'
    | 'shipped'
    | 'completed'
    | 'cancelled'
    | 'refunded'
    | 'failed'
    | 'checkout-draft';
  /**
   * Currency the order was created with, in ISO format.
   */
  currency?:
    | 'AED'
    | 'AFN'
    | 'ALL'
    | 'AMD'
    | 'ANG'
    | 'AOA'
    | 'ARS'
    | 'AUD'
    | 'AWG'
    | 'AZN'
    | 'BAM'
    | 'BBD'
    | 'BDT'
    | 'BGN'
    | 'BHD'
    | 'BIF'
    | 'BMD'
    | 'BND'
    | 'BOB'
    | 'BRL'
    | 'BSD'
    | 'BTC'
    | 'BTN'
    | 'BWP'
    | 'BYR'
    | 'BYN'
    | 'BZD'
    | 'CAD'
    | 'CDF'
    | 'CHF'
    | 'CLP'
    | 'CNY'
    | 'COP'
    | 'CRC'
    | 'CUC'
    | 'CUP'
    | 'CVE'
    | 'CZK'
    | 'DJF'
    | 'DKK'
    | 'DOP'
    | 'DZD'
    | 'EGP'
    | 'ERN'
    | 'ETB'
    | 'EUR'
    | 'FJD'
    | 'FKP'
    | 'GBP'
    | 'GEL'
    | 'GGP'
    | 'GHS'
    | 'GIP'
    | 'GMD'
    | 'GNF'
    | 'GTQ'
    | 'GYD'
    | 'HKD'
    | 'HNL'
    | 'HRK'
    | 'HTG'
    | 'HUF'
    | 'IDR'
    | 'ILS'
    | 'IMP'
    | 'INR'
    | 'IQD'
    | 'IRR'
    | 'IRT'
    | 'ISK'
    | 'JEP'
    | 'JMD'
    | 'JOD'
    | 'JPY'
    | 'KES'
    | 'KGS'
    | 'KHR'
    | 'KMF'
    | 'KPW'
    | 'KRW'
    | 'KWD'
    | 'KYD'
    | 'KZT'
    | 'LAK'
    | 'LBP'
    | 'LKR'
    | 'LRD'
    | 'LSL'
    | 'LYD'
    | 'MAD'
    | 'MDL'
    | 'MGA'
    | 'MKD'
    | 'MMK'
    | 'MNT'
    | 'MOP'
    | 'MRU'
    | 'MUR'
    | 'MVR'
    | 'MWK'
    | 'MXN'
    | 'MYR'
    | 'MZN'
    | 'NAD'
    | 'NGN'
    | 'NIO'
    | 'NOK'
    | 'NPR'
    | 'NZD'
    | 'OMR'
    | 'PAB'
    | 'PEN'
    | 'PGK'
    | 'PHP'
    | 'PKR'
    | 'PLN'
    | 'PRB'
    | 'PYG'
    | 'QAR'
    | 'RON'
    | 'RSD'
    | 'RUB'
    | 'RWF'
    | 'SAR'
    | 'SBD'
    | 'SCR'
    | 'SDG'
    | 'SEK'
    | 'SGD'
    | 'SHP'
    | 'SLL'
    | 'SOS'
    | 'SRD'
    | 'SSP'
    | 'STN'
    | 'SYP'
    | 'SZL'
    | 'THB'
    | 'TJS'
    | 'TMT'
    | 'TND'
    | 'TOP'
    | 'TRY'
    | 'TTD'
    | 'TWD'
    | 'TZS'
    | 'UAH'
    | 'UGX'
    | 'USD'
    | 'UYU'
    | 'UZS'
    | 'VEF'
    | 'VES'
    | 'VND'
    | 'VUV'
    | 'WST'
    | 'XAF'
    | 'XCD'
    | 'XOF'
    | 'XPF'
    | 'YER'
    | 'ZAR'
    | 'ZMW'
    | 'LTC'
    | 'ETH'
    | 'ZWL';
  /**
   * The date the order was created, in the site's timezone.
   */
  date_created?: {
    [k: string]: unknown;
  };
  /**
   * The date the order was created, as GMT.
   */
  date_created_gmt?: {
    [k: string]: unknown;
  };
  /**
   * The date the order was last modified, in the site's timezone.
   */
  date_modified?: {
    [k: string]: unknown;
  };
  /**
   * The date the order was last modified, as GMT.
   */
  date_modified_gmt?: {
    [k: string]: unknown;
  };
  /**
   * Total discount amount for the order.
   */
  discount_total?: string;
  /**
   * Total discount tax amount for the order.
   */
  discount_tax?: string;
  /**
   * Total shipping amount for the order.
   */
  shipping_total?: string;
  /**
   * Total shipping tax amount for the order.
   */
  shipping_tax?: string;
  /**
   * Sum of line item taxes only.
   */
  cart_tax?: string;
  /**
   * Grand total.
   */
  total?: string;
  /**
   * Sum of all taxes.
   */
  total_tax?: string;
  /**
   * True the prices included tax during checkout.
   */
  prices_include_tax?: boolean;
  /**
   * User ID who owns the order. 0 for guests.
   */
  customer_id?: number;
  /**
   * Customer's IP address.
   */
  customer_ip_address?: string;
  /**
   * User agent of the customer.
   */
  customer_user_agent?: string;
  /**
   * Note left by customer during checkout.
   */
  customer_note?: string;
  /**
   * Billing address.
   */
  billing?: {
    /**
     * First name.
     */
    first_name?: string;
    /**
     * Last name.
     */
    last_name?: string;
    /**
     * Company name.
     */
    company?: string;
    /**
     * Address line 1
     */
    address_1?: string;
    /**
     * Address line 2
     */
    address_2?: string;
    /**
     * City name.
     */
    city?: string;
    /**
     * ISO code or name of the county, state, province or district.
     */
    state?: string;
    /**
     * Postal code.
     */
    postcode?: string;
    /**
     * Country code in ISO 3166-1 alpha-2 format.
     */
    country?: string;
    /**
     * Email address.
     */
    email?: string | null;
    /**
     * Phone number.
     */
    phone?: string;
    [k: string]: unknown;
  };
  /**
   * Shipping address.
   */
  shipping?: {
    /**
     * First name.
     */
    first_name?: string;
    /**
     * Last name.
     */
    last_name?: string;
    /**
     * Company name.
     */
    company?: string;
    /**
     * Address line 1
     */
    address_1?: string;
    /**
     * Address line 2
     */
    address_2?: string;
    /**
     * City name.
     */
    city?: string;
    /**
     * ISO code or name of the county, state, province or district.
     */
    state?: string;
    /**
     * Postal code.
     */
    postcode?: string;
    /**
     * Country code in ISO 3166-1 alpha-2 format.
     */
    country?: string;
    [k: string]: unknown;
  };
  /**
   * Payment method ID.
   */
  payment_method?: string;
  /**
   * Payment method title.
   */
  payment_method_title?: string;
  /**
   * Unique transaction ID.
   */
  transaction_id?: string;
  /**
   * The date the order was paid, in the site's timezone.
   */
  date_paid?: {
    [k: string]: unknown;
  };
  /**
   * The date the order was paid, as GMT.
   */
  date_paid_gmt?: {
    [k: string]: unknown;
  };
  /**
   * The date the order was completed, in the site's timezone.
   */
  date_completed?: {
    [k: string]: unknown;
  };
  /**
   * The date the order was completed, as GMT.
   */
  date_completed_gmt?: {
    [k: string]: unknown;
  };
  /**
   * MD5 hash of basket items to ensure orders are not modified.
   */
  cart_hash?: string;
  /**
   * Meta data.
   */
  meta_data?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Line items data.
   */
  line_items?: {
    /**
     * Item ID.
     */
    id?: number;
    /**
     * Product name.
     */
    name?: {
      [k: string]: unknown;
    };
    /**
     * Parent product name if the product is a variation.
     */
    parent_name?: string;
    /**
     * Product ID.
     */
    product_id?: {
      [k: string]: unknown;
    };
    /**
     * Variation ID, if applicable.
     */
    variation_id?: number;
    /**
     * Quantity ordered.
     */
    quantity?: number;
    /**
     * Tax class of product.
     */
    tax_class?: string;
    /**
     * Line subtotal (before discounts).
     */
    subtotal?: string;
    /**
     * Line subtotal tax (before discounts).
     */
    subtotal_tax?: string;
    /**
     * Line total (after discounts).
     */
    total?: string;
    /**
     * Line total tax (after discounts).
     */
    total_tax?: string;
    /**
     * Line taxes.
     */
    taxes?: {
      /**
       * Tax rate ID
       */
      id?: number;
      /**
       * Tax total.
       */
      total?: string;
      /**
       * Tax subtotal.
       */
      subtotal?: string;
      [k: string]: unknown;
    }[];
    /**
     * Meta data.
     */
    meta_data?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: {
        [k: string]: unknown;
      };
      /**
       * Meta key for UI display.
       */
      display_key?: string;
      /**
       * Meta value for UI display.
       */
      display_value?: string;
      [k: string]: unknown;
    }[];
    /**
     * Product SKU.
     */
    sku?: string;
    /**
     * GTIN, UPC, EAN or ISBN.
     */
    global_unique_id?: string;
    /**
     * Product price.
     */
    price?: number;
    /**
     * Properties of the main product image.
     */
    image?: {
      /**
       * Image ID.
       */
      id?: number;
      /**
       * Image URL.
       */
      src?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Tax lines data.
   */
  tax_lines?: {
    /**
     * Item ID.
     */
    id?: number;
    /**
     * Tax rate code.
     */
    rate_code?: string;
    /**
     * Tax rate ID
     */
    rate_id?: number;
    /**
     * Tax rate label.
     */
    label?: string;
    /**
     * Show if is a compound tax rate.
     */
    compound?: boolean;
    /**
     * Tax total (not including shipping taxes).
     */
    tax_total?: string;
    /**
     * Shipping tax total.
     */
    shipping_tax_total?: string;
    /**
     * Meta data.
     */
    meta_data?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  /**
   * Shipping lines data.
   */
  shipping_lines?: {
    /**
     * Item ID.
     */
    id?: number;
    /**
     * Shipping method name.
     */
    method_title?: {
      [k: string]: unknown;
    };
    /**
     * Shipping method ID.
     */
    method_id?: {
      [k: string]: unknown;
    };
    /**
     * Shipping instance ID.
     */
    instance_id?: string;
    /**
     * Line total (after discounts).
     */
    total?: string;
    /**
     * Line total tax (after discounts).
     */
    total_tax?: string;
    /**
     * Line taxes.
     */
    taxes?: {
      /**
       * Tax rate ID
       */
      id?: number;
      /**
       * Tax total.
       */
      total?: string;
      [k: string]: unknown;
    }[];
    /**
     * Meta data.
     */
    meta_data?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  /**
   * Fee lines data.
   */
  fee_lines?: {
    /**
     * Item ID.
     */
    id?: number;
    /**
     * Fee name.
     */
    name?: {
      [k: string]: unknown;
    };
    /**
     * Tax class of fee.
     */
    tax_class?: string;
    /**
     * Tax status of fee.
     */
    tax_status?: 'taxable' | 'none';
    /**
     * Line total (after discounts).
     */
    total?: string;
    /**
     * Line total tax (after discounts).
     */
    total_tax?: string;
    /**
     * Line taxes.
     */
    taxes?: {
      /**
       * Tax rate ID
       */
      id?: number;
      /**
       * Tax total.
       */
      total?: string;
      /**
       * Tax subtotal.
       */
      subtotal?: string;
      [k: string]: unknown;
    }[];
    /**
     * Meta data.
     */
    meta_data?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  /**
   * Coupons line data.
   */
  coupon_lines?: {
    /**
     * Item ID.
     */
    id?: number;
    /**
     * Coupon code.
     */
    code?: {
      [k: string]: unknown;
    };
    /**
     * Discount total.
     */
    discount?: string;
    /**
     * Discount total tax.
     */
    discount_tax?: string;
    /**
     * Discount type.
     */
    discount_type?: string;
    /**
     * Discount amount as defined in the coupon (absolute value or a percent, depending on the discount type).
     */
    nominal_amount?: number;
    /**
     * Whether the coupon grants free shipping or not.
     */
    free_shipping?: boolean;
    /**
     * Meta data.
     */
    meta_data?: {
      /**
       * Meta ID.
       */
      id?: number;
      /**
       * Meta key.
       */
      key?: string;
      /**
       * Meta value.
       */
      value?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  /**
   * List of refunds.
   */
  refunds?: {
    /**
     * Refund ID.
     */
    id?: number;
    /**
     * Refund reason.
     */
    reason?: string;
    /**
     * Refund total.
     */
    total?: string;
    [k: string]: unknown;
  }[];
  /**
   * Order payment URL.
   */
  payment_url?: string;
  /**
   * Define if the order is paid. It will set the status to processing and reduce stock items.
   */
  set_paid?: boolean;
  /**
   * Whether an order can be edited.
   */
  is_editable?: boolean;
  /**
   * Whether an order needs payment, based on status and order total.
   */
  needs_payment?: boolean;
  /**
   * Whether an order needs processing before it can be completed.
   */
  needs_processing?: boolean;
  /**
   * Set the action as manual so that the order note registers as "added by user".
   */
  manual_update?: boolean;
  [k: string]: unknown;
}
