 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, change the source JSONSchema file,
 * and run generate-woocommerce-types.js to regenerate this file.
 */

export interface Product {
  /**
   * Unique identifier for the resource.
   */
  id?: number;
  /**
   * Product name.
   */
  name?: string;
  /**
   * Product slug.
   */
  slug?: string;
  /**
   * Product URL.
   */
  permalink?: string;
  /**
   * The date the product was created, in the site's timezone.
   */
  date_created?: {
    [k: string]: unknown;
  };
  /**
   * The date the product was created, as GMT.
   */
  date_created_gmt?: {
    [k: string]: unknown;
  };
  /**
   * The date the product was last modified, in the site's timezone.
   */
  date_modified?: {
    [k: string]: unknown;
  };
  /**
   * The date the product was last modified, as GMT.
   */
  date_modified_gmt?: {
    [k: string]: unknown;
  };
  /**
   * Product type.
   */
  type?: 'simple' | 'grouped' | 'external' | 'variable';
  /**
   * Product status (post status).
   */
  status?: 'draft' | 'pending' | 'private' | 'publish' | 'future' | 'auto-draft' | 'trash';
  /**
   * Featured product.
   */
  featured?: boolean;
  /**
   * Catalogue visibility.
   */
  catalog_visibility?: 'visible' | 'catalog' | 'search' | 'hidden';
  /**
   * Product description.
   */
  description?: string;
  /**
   * Product short description.
   */
  short_description?: string;
  /**
   * Stock Keeping Unit.
   */
  sku?: string;
  /**
   * GTIN, UPC, EAN or ISBN.
   */
  global_unique_id?: string;
  /**
   * Current product price.
   */
  price?: string;
  /**
   * Product regular price.
   */
  regular_price?: string;
  /**
   * Product sale price.
   */
  sale_price?: string;
  /**
   * Start date of sale price, in the site's timezone.
   */
  date_on_sale_from?: {
    [k: string]: unknown;
  };
  /**
   * Start date of sale price, as GMT.
   */
  date_on_sale_from_gmt?: {
    [k: string]: unknown;
  };
  /**
   * End date of sale price, in the site's timezone.
   */
  date_on_sale_to?: {
    [k: string]: unknown;
  };
  /**
   * End date of sale price, in the site's timezone.
   */
  date_on_sale_to_gmt?: {
    [k: string]: unknown;
  };
  /**
   * Price formatted in HTML.
   */
  price_html?: string;
  /**
   * Shows if the product is on sale.
   */
  on_sale?: boolean;
  /**
   * Shows if the product can be bought.
   */
  purchasable?: boolean;
  /**
   * Amount of sales.
   */
  total_sales?: number;
  /**
   * If the product is virtual.
   */
  virtual?: boolean;
  /**
   * If the product is downloadable.
   */
  downloadable?: boolean;
  /**
   * List of downloadable files.
   */
  downloads?: {
    /**
     * File ID.
     */
    id?: string;
    /**
     * File name.
     */
    name?: string;
    /**
     * File URL.
     */
    file?: string;
    [k: string]: unknown;
  }[];
  /**
   * Number of times downloadable files can be downloaded after purchase.
   */
  download_limit?: number;
  /**
   * Number of days until access to downloadable files expires.
   */
  download_expiry?: number;
  /**
   * Product external URL. Only for external products.
   */
  external_url?: string;
  /**
   * Product external button text. Only for external products.
   */
  button_text?: string;
  /**
   * Tax status.
   */
  tax_status?: 'taxable' | 'shipping' | 'none';
  /**
   * Tax class.
   */
  tax_class?: string;
  /**
   * Stock management at product level.
   */
  manage_stock?: boolean;
  /**
   * Stock quantity.
   */
  stock_quantity?: number;
  /**
   * Controls the stock status of the product.
   */
  stock_status?: 'instock' | 'outofstock' | 'onbackorder';
  /**
   * If managing stock, this controls if back-orders are allowed.
   */
  backorders?: 'no' | 'notify' | 'yes';
  /**
   * Shows if back-orders are allowed.
   */
  backorders_allowed?: boolean;
  /**
   * Shows if the product is on back-order.
   */
  backordered?: boolean;
  /**
   * Low Stock amount for the product.
   */
  low_stock_amount?: number | null;
  /**
   * Allow one item to be bought in a single order.
   */
  sold_individually?: boolean;
  /**
   * Product weight (kg).
   */
  weight?: string;
  /**
   * Product dimensions.
   */
  dimensions?: {
    /**
     * Product length (cm).
     */
    length?: string;
    /**
     * Product width (cm).
     */
    width?: string;
    /**
     * Product height (cm).
     */
    height?: string;
    [k: string]: unknown;
  };
  /**
   * Shows if the product need to be shipped.
   */
  shipping_required?: boolean;
  /**
   * Shows whether or not the product shipping is taxable.
   */
  shipping_taxable?: boolean;
  /**
   * Shipping class slug.
   */
  shipping_class?: string;
  /**
   * Shipping class ID.
   */
  shipping_class_id?: string;
  /**
   * Allow reviews.
   */
  reviews_allowed?: boolean;
  /**
   * Post password.
   */
  post_password?: string;
  /**
   * Reviews average rating.
   */
  average_rating?: string;
  /**
   * Amount of reviews that the product has.
   */
  rating_count?: number;
  /**
   * List of related products IDs.
   */
  related_ids?: number[];
  /**
   * List of up-sell products IDs.
   */
  upsell_ids?: number[];
  /**
   * List of cross-sell products IDs.
   */
  cross_sell_ids?: number[];
  /**
   * Product parent ID.
   */
  parent_id?: number;
  /**
   * Optional note to send the customer after purchase.
   */
  purchase_note?: string;
  /**
   * List of categories.
   */
  categories?: {
    /**
     * Category ID.
     */
    id?: number;
    /**
     * Category name.
     */
    name?: string;
    /**
     * Category slug.
     */
    slug?: string;
    [k: string]: unknown;
  }[];
  /**
   * List of brands.
   */
  brands?: {
    /**
     * Brand ID.
     */
    id?: number;
    /**
     * Brand name.
     */
    name?: string;
    /**
     * Brand slug.
     */
    slug?: string;
    [k: string]: unknown;
  }[];
  /**
   * List of tags.
   */
  tags?: {
    /**
     * Tag ID.
     */
    id?: number;
    /**
     * Tag name.
     */
    name?: string;
    /**
     * Tag slug.
     */
    slug?: string;
    [k: string]: unknown;
  }[];
  /**
   * List of images.
   */
  images?: {
    /**
     * Image ID.
     */
    id?: number;
    /**
     * The date the image was created, in the site's timezone.
     */
    date_created?: {
      [k: string]: unknown;
    };
    /**
     * The date the image was created, as GMT.
     */
    date_created_gmt?: {
      [k: string]: unknown;
    };
    /**
     * The date the image was last modified, in the site's timezone.
     */
    date_modified?: {
      [k: string]: unknown;
    };
    /**
     * The date the image was last modified, as GMT.
     */
    date_modified_gmt?: {
      [k: string]: unknown;
    };
    /**
     * Image URL.
     */
    src?: string;
    /**
     * Image name.
     */
    name?: string;
    /**
     * Image alternative text.
     */
    alt?: string;
    [k: string]: unknown;
  }[];
  /**
   * Shows if the product needs to be configured before it can be bought.
   */
  has_options?: boolean;
  /**
   * List of attributes.
   */
  attributes?: {
    /**
     * Attribute ID.
     */
    id?: number;
    /**
     * Attribute name.
     */
    name?: string;
    /**
     * Attribute position.
     */
    position?: number;
    /**
     * Define if the attribute is visible on the "Additional information" tab in the product's page.
     */
    visible?: boolean;
    /**
     * Define if the attribute can be used as variation.
     */
    variation?: boolean;
    /**
     * List of available term names of the attribute.
     */
    options?: string[];
    [k: string]: unknown;
  }[];
  /**
   * Defaults variation attributes.
   */
  default_attributes?: {
    /**
     * Attribute ID.
     */
    id?: number;
    /**
     * Attribute name.
     */
    name?: string;
    /**
     * Selected attribute term name.
     */
    option?: string;
    [k: string]: unknown;
  }[];
  /**
   * List of variations IDs.
   */
  variations?: number[];
  /**
   * List of grouped products ID.
   */
  grouped_products?: number[];
  /**
   * Menu order, used to custom sort products.
   */
  menu_order?: number;
  /**
   * Meta data.
   */
  meta_data?: {
    /**
     * Meta ID.
     */
    id?: number;
    /**
     * Meta key.
     */
    key?: string;
    /**
     * Meta value.
     */
    value?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Permalink template for the product.
   */
  permalink_template?: string;
  /**
   * Slug automatically generated from the product name.
   */
  generated_slug?: string;
  [k: string]: unknown;
}
