/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/catalog/v0/categories": {
    /**
     * Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 1 | 2 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["listCatalogCategories"];
  };
}

export interface CatalogItemsV0Schema {
  ListCatalogCategoriesResponse: {
    /** @description The payload for the listCatalogCategories operation. */
    payload?: CatalogItemsV0Schema["ListOfCategories"];
    /** @description One or more unexpected errors occurred during the listCatalogCategories operation. */
    errors?: CatalogItemsV0Schema["ErrorList"];
  };
  ListOfCategories: CatalogItemsV0Schema["Categories"][];
  Categories: {
    /** @description The identifier for the product category (or browse node). */
    ProductCategoryId?: string;
    /** @description The name of the product category (or browse node). */
    ProductCategoryName?: string;
    /** @description The parent product category. */
    parent?: { [key: string]: unknown };
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: CatalogItemsV0Schema["Error"][];
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition in a human-readable form. */
    message: string;
    /** @description Additional information that can help the caller understand or fix the issue. */
    details?: string;
  };
}

export interface operations {
  /**
   * Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 1 | 2 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
   */
  listCatalogCategories: {
    parameters: {
      query: {
        /** A marketplace identifier. Specifies the marketplace for the item. */
        MarketplaceId: string;
        /** The Amazon Standard Identification Number (ASIN) of the item. */
        ASIN?: string;
        /** Used to identify items in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit. */
        SellerSKU?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: CatalogItemsV0Schema["ListCatalogCategoriesResponse"];
      };
    };
  };
}

export interface external {}

export default CatalogItemsV0Schema;
