/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/catalog/2022-04-01/items": {
    /**
     * Search for a list of Amazon catalog items and item-related information. You can search by identifier or by keywords.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 2 | 2 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["searchCatalogItems"];
  };
  "/catalog/2022-04-01/items/{asin}": {
    /**
     * Retrieves details for an item in the Amazon catalog.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 2 | 2 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getCatalogItem"];
  };
}

export interface CatalogItemsSchema {
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition. */
    message: string;
    /** @description Additional details that can help the caller understand or fix the issue. */
    details?: string;
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: {
    /** @description A list of error responses returned when a request is unsuccessful. */
    errors: CatalogItemsSchema["Error"][];
  };
  /** @description An item in the Amazon catalog. */
  Item: {
    asin: CatalogItemsSchema["ItemAsin"];
    attributes?: CatalogItemsSchema["ItemAttributes"];
    classifications?: CatalogItemsSchema["ItemBrowseClassifications"];
    dimensions?: CatalogItemsSchema["ItemDimensions"];
    identifiers?: CatalogItemsSchema["ItemIdentifiers"];
    images?: CatalogItemsSchema["ItemImages"];
    productTypes?: CatalogItemsSchema["ItemProductTypes"];
    relationships?: CatalogItemsSchema["ItemRelationships"];
    salesRanks?: CatalogItemsSchema["ItemSalesRanks"];
    summaries?: CatalogItemsSchema["ItemSummaries"];
    vendorDetails?: CatalogItemsSchema["ItemVendorDetails"];
  };
  /** @description The unique identifier of an item in the Amazon catalog. */
  ItemAsin: string;
  /** @description A JSON object containing structured item attribute data that is keyed by attribute name. Catalog item attributes conform to the related Amazon product type definitions that you can get from the [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/reference/product-type-definitions-v2020-09-01). */
  ItemAttributes: { [key: string]: unknown };
  /** @description Classification (browse node) for an Amazon catalog item. */
  ItemBrowseClassification: {
    /** @description Display name for the classification. */
    displayName: string;
    /** @description Identifier of the classification. */
    classificationId: string;
    /** @description Parent classification of the current classification. */
    parent?: CatalogItemsSchema["ItemBrowseClassification"];
  };
  /** @description Individual contributor to the creation of an item, such as an author or actor. */
  ItemContributor: {
    role: CatalogItemsSchema["ItemContributorRole"];
    /** @description Name of the contributor, such as `Jane Austen`. */
    value: string;
  };
  /** @description Role of an individual contributor in the creation of an item, such as author or actor. */
  ItemContributorRole: {
    /** @description Display name of the role in the requested locale, such as `Author` or `Actor`. */
    displayName?: string;
    /** @description Role value for the Amazon catalog item, such as `author` or `actor`. */
    value: string;
  };
  /** @description An array of classifications (browse nodes) that is associated with the item in the Amazon catalog, grouped by `marketplaceId`. */
  ItemBrowseClassifications: CatalogItemsSchema["ItemBrowseClassificationsByMarketplace"][];
  /** @description Classifications (browse nodes) that are associated with the item in the Amazon catalog for the indicated `marketplaceId`. */
  ItemBrowseClassificationsByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description Classifications (browse nodes) that are associated with the item in the Amazon catalog. */
    classifications?: CatalogItemsSchema["ItemBrowseClassification"][];
  };
  /** @description The value of an individual dimension for an Amazon catalog item or item package. */
  Dimension: {
    /** @description Unit of measurement for the dimension value. */
    unit?: string;
    /** @description Numeric value of the dimension. */
    value?: number;
  };
  /** @description Dimensions of an Amazon catalog item or item in its packaging. */
  Dimensions: {
    /** @description Height of an item or item package. */
    height?: CatalogItemsSchema["Dimension"];
    /** @description Length of an item or item package. */
    length?: CatalogItemsSchema["Dimension"];
    /** @description Weight of an item or item package. */
    weight?: CatalogItemsSchema["Dimension"];
    /** @description Width of an item or item package. */
    width?: CatalogItemsSchema["Dimension"];
  };
  /** @description An array of dimensions that are associated with the item in the Amazon catalog, grouped by `marketplaceId`. */
  ItemDimensions: CatalogItemsSchema["ItemDimensionsByMarketplace"][];
  /** @description Dimensions that are associated with the item in the Amazon catalog for the indicated `marketplaceId`. */
  ItemDimensionsByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description Dimensions of an Amazon catalog item. */
    item?: CatalogItemsSchema["Dimensions"];
    /** @description Dimensions of a package that contains an Amazon catalog item. */
    package?: CatalogItemsSchema["Dimensions"];
  };
  /** @description Identifiers associated with the item in the Amazon catalog, such as UPC and EAN identifiers. */
  ItemIdentifiers: CatalogItemsSchema["ItemIdentifiersByMarketplace"][];
  /** @description Identifiers that are associated with the item in the Amazon catalog, grouped by `marketplaceId`. */
  ItemIdentifiersByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).identifier. */
    marketplaceId: string;
    /** @description Identifiers associated with the item in the Amazon catalog for the indicated `marketplaceId`. */
    identifiers: CatalogItemsSchema["ItemIdentifier"][];
  };
  /** @description The identifier that is associated with the item in the Amazon catalog, such as a UPC or EAN identifier. */
  ItemIdentifier: {
    /** @description Type of identifier, such as UPC, EAN, or ISBN. */
    identifierType: string;
    /** @description Identifier of the item. */
    identifier: string;
  };
  /** @description The images for an item in the Amazon catalog. */
  ItemImages: CatalogItemsSchema["ItemImagesByMarketplace"][];
  /** @description Images for an item in the Amazon catalog, grouped by `marketplaceId`. */
  ItemImagesByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description Images for an item in the Amazon catalog, grouped by `marketplaceId`. */
    images: CatalogItemsSchema["ItemImage"][];
  };
  /** @description Image for an item in the Amazon catalog. */
  ItemImage: {
    /**
     * @description Variant of the image, such as `MAIN` or `PT01`.
     * @example MAIN
     * @enum {string}
     */
    variant:
      | "MAIN"
      | "PT01"
      | "PT02"
      | "PT03"
      | "PT04"
      | "PT05"
      | "PT06"
      | "PT07"
      | "PT08"
      | "SWCH";
    /** @description URL for the image. */
    link: string;
    /** @description Height of the image in pixels. */
    height: number;
    /** @description Width of the image in pixels. */
    width: number;
  };
  /** @description Product types that are associated with the Amazon catalog item. */
  ItemProductTypes: CatalogItemsSchema["ItemProductTypeByMarketplace"][];
  /** @description Product type that is associated with the Amazon catalog item, grouped by `marketplaceId`. */
  ItemProductTypeByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId?: string;
    /**
     * @description Name of the product type that is associated with the Amazon catalog item.
     * @example LUGGAGE
     */
    productType?: string;
  };
  /** @description Sales ranks of an Amazon catalog item. */
  ItemSalesRanks: CatalogItemsSchema["ItemSalesRanksByMarketplace"][];
  /** @description Sales ranks of an Amazon catalog item, grouped by `marketplaceId`. */
  ItemSalesRanksByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description Sales ranks of an Amazon catalog item for a `marketplaceId`, grouped by classification. */
    classificationRanks?: CatalogItemsSchema["ItemClassificationSalesRank"][];
    /** @description Sales ranks of an Amazon catalog item for a `marketplaceId`, grouped by website display group. */
    displayGroupRanks?: CatalogItemsSchema["ItemDisplayGroupSalesRank"][];
  };
  /** @description Sales rank of an Amazon catalog item. */
  ItemClassificationSalesRank: {
    /** @description Identifier of the classification that is associated with the sales rank. */
    classificationId: string;
    /** @description Name of the sales rank. */
    title: string;
    /** @description Corresponding Amazon retail website URL for the sales category. */
    link?: string;
    /** @description Sales rank. */
    rank: number;
  };
  /** @description Sales rank of an Amazon catalog item, grouped by website display group. */
  ItemDisplayGroupSalesRank: {
    /** @description Name of the website display group that is associated with the sales rank */
    websiteDisplayGroup: string;
    /** @description Name of the sales rank. */
    title: string;
    /** @description Corresponding Amazon retail website URL for the sales rank. */
    link?: string;
    /** @description Sales rank. */
    rank: number;
  };
  /** @description Summaries of Amazon catalog items. */
  ItemSummaries: CatalogItemsSchema["ItemSummaryByMarketplace"][];
  /** @description Information about an Amazon catalog item for the indicated `marketplaceId`. */
  ItemSummaryByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description When `true`, the Amazon catalog item is intended for an adult audience or is sexual in nature. */
    adultProduct?: boolean;
    /** @description When `true`, the Amazon catalog item is autographed. */
    autographed?: boolean;
    /** @description Name of the brand that is associated with the Amazon catalog item. */
    brand?: string;
    /** @description Classification (browse node) that is associated with the Amazon catalog item. */
    browseClassification?: CatalogItemsSchema["ItemBrowseClassification"];
    /** @description The color that is associated with the Amazon catalog item. */
    color?: string;
    /** @description Individual contributors to the creation of the item, such as the authors or actors. */
    contributors?: CatalogItemsSchema["ItemContributor"][];
    /**
     * @description Classification type that is associated with the Amazon catalog item.
     * @enum {string}
     */
    itemClassification?:
      | "BASE_PRODUCT"
      | "OTHER"
      | "PRODUCT_BUNDLE"
      | "VARIATION_PARENT";
    /** @description The name that is associated with the Amazon catalog item. */
    itemName?: string;
    /** @description The name of the manufacturer that is associated with the Amazon catalog item. */
    manufacturer?: string;
    /** @description When true, the item is classified as memorabilia. */
    memorabilia?: boolean;
    /** @description The model number that is associated with the Amazon catalog item. */
    modelNumber?: string;
    /** @description The quantity of the Amazon catalog item within one package. */
    packageQuantity?: number;
    /** @description The part number that is associated with the Amazon catalog item. */
    partNumber?: string;
    /**
     * Format: date
     * @description The earliest date on which the Amazon catalog item can be shipped to customers.
     */
    releaseDate?: string;
    /** @description The name of the size of the Amazon catalog item. */
    size?: string;
    /** @description The name of the style that is associated with the Amazon catalog item. */
    style?: string;
    /** @description When true, the Amazon catalog item is eligible for trade-in. */
    tradeInEligible?: boolean;
    /** @description The identifier of the website display group that is associated with the Amazon catalog item. */
    websiteDisplayGroup?: string;
    /** @description The display name of the website display group that is associated with the Amazon catalog item. */
    websiteDisplayGroupName?: string;
  };
  /** @description The variation theme is a list of Amazon catalog item attributes that define the variation family. */
  ItemVariationTheme: {
    /** @description Names of the Amazon catalog item attributes that are associated with the variation theme. */
    attributes?: string[];
    /**
     * @description Variation theme that indicates the combination of Amazon catalog item attributes that define the variation family.
     * @example COLOR_NAME/STYLE_NAME
     */
    theme?: string;
  };
  /** @description Relationships grouped by `marketplaceId` for an Amazon catalog item (for example, variations). */
  ItemRelationships: CatalogItemsSchema["ItemRelationshipsByMarketplace"][];
  /** @description Relationship details for the Amazon catalog item for the specified Amazon `marketplaceId`. */
  ItemRelationshipsByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description Relationships for the item. */
    relationships: CatalogItemsSchema["ItemRelationship"][];
  };
  /** @description Relationship details for an Amazon catalog item. */
  ItemRelationship: {
    /** @description ASINs of the related items that are children of this item. */
    childAsins?: string[];
    /** @description ASINs of the related items that are parents of this item. */
    parentAsins?: string[];
    /** @description For `VARIATION` relationships, the variation theme indicates the combination of Amazon catalog item attributes that define the variation family. */
    variationTheme?: CatalogItemsSchema["ItemVariationTheme"];
    /**
     * @description Type of relationship.
     * @example VARIATION
     * @enum {string}
     */
    type: "VARIATION" | "PACKAGE_HIERARCHY";
  };
  /** @description The product category or subcategory that is associated with an Amazon catalog item. */
  ItemVendorDetailsCategory: {
    /** @description The display name of the product category or subcategory. */
    displayName?: string;
    /** @description The code that identifies the product category or subcategory. */
    value?: string;
  };
  /** @description The vendor details that are associated with an Amazon catalog item. Vendor details are only available to vendors. */
  ItemVendorDetails: CatalogItemsSchema["ItemVendorDetailsByMarketplace"][];
  /** @description The vendor details that are associated with an Amazon catalog item for the specified `marketplaceId`. */
  ItemVendorDetailsByMarketplace: {
    /** @description Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: string;
    /** @description The brand code that is associated with an Amazon catalog item. */
    brandCode?: string;
    /** @description The manufacturer code that is associated with an Amazon catalog item. */
    manufacturerCode?: string;
    /** @description The parent vendor code of the manufacturer code. */
    manufacturerCodeParent?: string;
    /** @description The product category that is associated with an Amazon catalog item. */
    productCategory?: CatalogItemsSchema["ItemVendorDetailsCategory"];
    /** @description The product group that is associated with an Amazon catalog item. */
    productGroup?: string;
    /** @description The product subcategory that is associated with an Amazon catalog item. */
    productSubcategory?: CatalogItemsSchema["ItemVendorDetailsCategory"];
    /**
     * @description The replenishment category that is associated with an Amazon catalog item.
     * @enum {string}
     */
    replenishmentCategory?:
      | "ALLOCATED"
      | "BASIC_REPLENISHMENT"
      | "IN_SEASON"
      | "LIMITED_REPLENISHMENT"
      | "MANUFACTURER_OUT_OF_STOCK"
      | "NEW_PRODUCT"
      | "NON_REPLENISHABLE"
      | "NON_STOCKUPABLE"
      | "OBSOLETE"
      | "PLANNED_REPLENISHMENT";
  };
  /** @description Items in the Amazon catalog and search-related metadata. */
  ItemSearchResults: {
    /**
     * @description For searches that are based on `identifiers`, `numberOfResults` is the total number of Amazon catalog items found. For searches that are based on `keywords`, `numberOfResults` is the estimated total number of Amazon catalog items that are matched by the search query. Only results up to the page count limit are returned per request regardless of the number found.
     *
     * **Note:** The maximum number of items (ASINs) that can be returned and paged through is 1,000.
     */
    numberOfResults: number;
    /** @description The `nextToken` and `previousToken` values that are required to retrieve paginated results. */
    pagination?: CatalogItemsSchema["Pagination"];
    /** @description Search refinements for searches that are based on `keywords`. */
    refinements?: CatalogItemsSchema["Refinements"];
    /** @description A list of items from the Amazon catalog. */
    items: CatalogItemsSchema["Item"][];
  };
  /** @description Pagination occurs when a request produces a response that exceeds the `pageSize`. This means that the response is divided into individual pages. To retrieve the next page or the previous page of results, you must pass the `nextToken` value or the `previousToken` value as the `pageToken` parameter in the next request. There is no `nextToken` in the pagination object on the last page. */
  Pagination: {
    /** @description A token that you can use to retrieve the next page. */
    nextToken?: string;
    /** @description A token that you can use to retrieve the previous page. */
    previousToken?: string;
  };
  /** @description Optional fields that you can use to refine your search results. */
  Refinements: {
    /** @description A list of brands you can use to refine your search. */
    brands: CatalogItemsSchema["BrandRefinement"][];
    /** @description A list of classifications you can use to refine your search. */
    classifications: CatalogItemsSchema["ClassificationRefinement"][];
  };
  /** @description A brand that you can use to refine your search. */
  BrandRefinement: {
    /** @description The estimated number of results that would be returned if you refine your search by the specified `brandName`. */
    numberOfResults: number;
    /** @description The brand name that you can use to refine your search. */
    brandName: string;
  };
  /** @description A classification that you can use to refine your search. */
  ClassificationRefinement: {
    /** @description The estimated number of results that would be returned if you refine your search by the specified `classificationId`. */
    numberOfResults: number;
    /** @description Display name for the classification. */
    displayName: string;
    /** @description The identifier of the classification that you can use to refine your search. */
    classificationId: string;
  };
}

export interface operations {
  /**
   * Search for a list of Amazon catalog items and item-related information. You can search by identifier or by keywords.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 2 | 2 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  searchCatalogItems: {
    parameters: {
      query: {
        /** A comma-delimited list of product identifiers that you can use to search the Amazon catalog. **Note:** You cannot include `identifiers` and `keywords` in the same request. */
        identifiers?: string[];
        /** The type of product identifiers that you can use to search the Amazon catalog. **Note:** `identifiersType` is required when `identifiers` is in the request. */
        identifiersType?:
          | "ASIN"
          | "EAN"
          | "GTIN"
          | "ISBN"
          | "JAN"
          | "MINSAN"
          | "SKU"
          | "UPC";
        /** A comma-delimited list of Amazon marketplace identifiers. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
        marketplaceIds: string[];
        /** A comma-delimited list of datasets to include in the response. */
        includedData?: (
          | "attributes"
          | "classifications"
          | "dimensions"
          | "identifiers"
          | "images"
          | "productTypes"
          | "relationships"
          | "salesRanks"
          | "summaries"
          | "vendorDetails"
        )[];
        /** The locale for which you want to retrieve localized summaries. Defaults to the primary locale of the marketplace. */
        locale?: string;
        /** A selling partner identifier, such as a seller account or vendor code. **Note:** Required when `identifiersType` is `SKU`. */
        sellerId?: string;
        /** A comma-delimited list of keywords that you can use to search the Amazon catalog. **Note:** You cannot include `keywords` and `identifiers` in the same request. */
        keywords?: string[];
        /** A comma-delimited list of brand names that you can use to limit the search in queries based on `keywords`. **Note:** Cannot be used with `identifiers`. */
        brandNames?: string[];
        /** A comma-delimited list of classification identifiers that you can use to limit the search in queries based on `keywords`. **Note:** Cannot be used with `identifiers`. */
        classificationIds?: string[];
        /** The number of results to include on each page. */
        pageSize?: number;
        /** A token that you can use to fetch a specific page when there are multiple pages of results. */
        pageToken?: string;
        /** The language of the keywords that are included in queries based on `keywords`. Defaults to the primary locale of the marketplace. **Note:** Cannot be used with `identifiers`. */
        keywordsLocale?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: CatalogItemsSchema["ItemSearchResults"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
    };
  };
  /**
   * Retrieves details for an item in the Amazon catalog.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 2 | 2 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getCatalogItem: {
    parameters: {
      path: {
        /** The Amazon Standard Identification Number (ASIN) of the item. */
        asin: string;
      };
      query: {
        /** A comma-delimited list of Amazon marketplace identifiers. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
        marketplaceIds: string[];
        /** A comma-delimited list of datasets to include in the response. */
        includedData?: (
          | "attributes"
          | "classifications"
          | "dimensions"
          | "identifiers"
          | "images"
          | "productTypes"
          | "relationships"
          | "salesRanks"
          | "summaries"
          | "vendorDetails"
        )[];
        /** The locale for which you want to retrieve localized summaries. Defaults to the primary locale of the marketplace. */
        locale?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: CatalogItemsSchema["Item"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: CatalogItemsSchema["ErrorList"];
      };
    };
  };
}

export interface external {}

export default CatalogItemsSchema;
