/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/finances/2024-06-19/transactions": {
    /**
     * Returns transactions for the given parameters. Financial events might not include orders from the last 48 hours.
     *
     * **Usage plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 10 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).
     */
    get: operations["listTransactions"];
  };
}

export interface Finances2024Schema {
  /** @description The response schema for the `listTransactions` operation. */
  ListTransactionsResponse: {
    /** @description The payload for the `listTransactions` operation. */
    payload?: Finances2024Schema["TransactionsPayload"];
  };
  /** @description The payload for the `listTransactions` operation. */
  TransactionsPayload: {
    /** @description The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages. */
    nextToken?: string;
    transactions?: Finances2024Schema["Transactions"];
  };
  /** @description A list of transactions within the specified time period. */
  Transactions: Finances2024Schema["Transaction"][];
  /**
   * @description All the information related to a transaction.
   * @example {
   *   "sellingPartnerMetadata": {
   *     "sellingPartnerId": "XXXXXXXXXXXXXX",
   *     "accountType": "PAYABLE",
   *     "marketplaceId": "ATVPDKIKX0DER"
   *   },
   *   "relatedIdentifiers": [
   *     {
   *       "relatedIdentifierName": "ORDER_ID",
   *       "relatedIdentifierValue": "8129762527551"
   *     }
   *   ],
   *   "transactionType": "Shipment",
   *   "transactionId": "b1qD0oAliFkLiqRyGbmeT0DoS2Z2kHzi7TZ92z-vARI",
   *   "transactionStatus": "Released",
   *   "description": "Order Payment",
   *   "postedDate": "2020-07-14T03:35:13.214Z",
   *   "totalAmount": {
   *     "currencyAmount": 10,
   *     "currencyCode": "USD"
   *   },
   *   "marketplaceDetails": {
   *     "marketplaceId": "ATVPDKIKX0DER",
   *     "marketplaceName": "Amazon.com"
   *   },
   *   "items": [
   *     {
   *       "description": "Item title",
   *       "totalAmount": {
   *         "currencyAmount": 10,
   *         "currencyCode": "USD"
   *       },
   *       "relatedIdentifiers": [
   *         {
   *           "itemRelatedIdentifierName": "ORDER_ADJUSTMENT_ITEM_ID",
   *           "itemRelatedIdentifierValue": "81297625-121-27551"
   *         }
   *       ],
   *       "breakdowns": [
   *         {
   *           "breakdownType": "Product Charges",
   *           "breakdownAmount": {
   *             "currencyAmount": 10,
   *             "currencyCode": "USD"
   *           },
   *           "breakdowns": [
   *             {
   *               "breakdownType": "Principle",
   *               "breakdownAmount": {
   *                 "currencyAmount": 10,
   *                 "currencyCode": "USD"
   *               },
   *               "breakdowns": []
   *             }
   *           ]
   *         }
   *       ],
   *       "contexts": [
   *         {
   *           "contextType": "ProductContext",
   *           "asin": "B07FGXZQZ1",
   *           "sku": "sku-12",
   *           "quantityShipped": 1,
   *           "fulfillmentNetwork": "MFN"
   *         }
   *       ]
   *     }
   *   ],
   *   "breakdowns": {
   *     "breakdowns": [
   *       {
   *         "breakdownType": "Sales",
   *         "breakdownAmount": {
   *           "currencyAmount": 10,
   *           "currencyCode": "USD"
   *         },
   *         "breakdowns": [
   *           {
   *             "breakdownType": "Product Charges",
   *             "breakdownAmount": {
   *               "currencyAmount": 10,
   *               "currencyCode": "USD"
   *             },
   *             "breakdowns": []
   *           }
   *         ]
   *       }
   *     ]
   *   },
   *   "contexts": [
   *     {
   *       "contextType": "AmazonPayContext",
   *       "storeName": "Store 1",
   *       "orderType": "Order Type",
   *       "channel": "MFN"
   *     }
   *   ]
   * }
   */
  Transaction: {
    /** @description Metadata that describes the seller. */
    sellingPartnerMetadata?: Finances2024Schema["SellingPartnerMetadata"];
    /** @description Identifiers related to the transaction, such as order and shipment IDs. */
    relatedIdentifiers?: Finances2024Schema["RelatedIdentifiers"];
    /**
     * @description The type of transaction.
     *
     * **Possible value:** `Shipment`
     */
    transactionType?: string;
    /** @description The unique identifier of the transaction. */
    transactionId?: string;
    /**
     * @description The status of the transaction.
     *
     * **Possible values:**
     *
     * * `DEFERRED`: the transaction is currently deferred.
     * * `RELEASED`: the transaction is currently released.
     * * `DEFERRED_RELEASED`: the transaction was deferred in the past, but is now released. The status of a deferred transaction is updated to `DEFERRED_RELEASED` when the transaction is released.
     */
    transactionStatus?: string;
    /**
     * @description Describes the reasons for the transaction.
     *
     * **Example:** 'Order Payment', 'Refund Order'
     */
    description?: string;
    /** @description The date and time when the transaction was posted. */
    postedDate?: Finances2024Schema["Date"];
    /** @description The total amount of money in the transaction. */
    totalAmount?: Finances2024Schema["Currency"];
    /** @description Information about the marketplace where the transaction occurred. */
    marketplaceDetails?: Finances2024Schema["MarketplaceDetails"];
    /** @description Additional information about the items in the transaction. */
    items?: Finances2024Schema["Items"];
    /** @description Additional Information about the transaction. */
    contexts?: Finances2024Schema["Contexts"];
    /** @description A list of breakdowns that detail how the total amount is calculated for the transaction. */
    breakdowns?: Finances2024Schema["Breakdown"][];
  };
  /** @description A signed decimal number. */
  BigDecimal: number;
  /** @description A currency type and amount. */
  Currency: {
    /** @description The three-digit currency code in ISO 4217 format. */
    currencyCode?: string;
    /** @description The monetary value. */
    currencyAmount?: Finances2024Schema["BigDecimal"];
  };
  /** @description Metadata that describes the seller. */
  SellingPartnerMetadata: {
    /** @description A unique seller identifier. */
    sellingPartnerId?: string;
    /** @description The type of account in the transaction. */
    accountType?: string;
    /** @description The identifier of the marketplace where the transaction occurred. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId?: string;
  };
  /** @description Related business identifier of the transaction. */
  RelatedIdentifier: {
    /**
     * @description An enumerated set of related business identifier names.
     * @enum {string}
     */
    relatedIdentifierName?:
      | "ORDER_ID"
      | "SHIPMENT_ID"
      | "FINANCIAL_EVENT_GROUP_ID"
      | "REFUND_ID"
      | "INVOICE_ID"
      | "DISBURSEMENT_ID"
      | "TRANSFER_ID"
      | "DEFERRED_TRANSACTION_ID"
      | "RELEASE_TRANSACTION_ID"
      | "SETTLEMENT_ID";
    /** @description Corresponding value of `RelatedIdentifierName`. */
    relatedIdentifierValue?: string;
  };
  /** @description Related business identifiers of the transaction. */
  RelatedIdentifiers: Finances2024Schema["RelatedIdentifier"][];
  /**
   * Format: date-time
   * @description A date in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
   */
  Date: string;
  /**
   * @description Information about the marketplace where the transaction occurred.
   * @example {
   *   "marketplaceId": "ATVPDKIKX0DER",
   *   "marketplaceName": "Amazon.com"
   * }
   */
  MarketplaceDetails: {
    /** @description The identifier of the marketplace where the transaction occurred. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId?: string;
    /** @description The name of the marketplace where the transaction occurred. For example: `Amazon.com`,`Amazon.in` */
    marketplaceName?: string;
  };
  /** @description A list of items in the transaction. */
  Items: Finances2024Schema["Item"][];
  /** @description Additional information about the items in a transaction. */
  Item: {
    /** @description A description of the items in a transaction. */
    description?: string;
    /** @description Related business identifiers of the item. */
    relatedIdentifiers?: Finances2024Schema["ItemRelatedIdentifiers"];
    /** @description The total monetary amount of the item. */
    totalAmount?: Finances2024Schema["Currency"];
    /** @description A list of breakdowns that detail how the total amount is calculated for the transaction. */
    breakdowns?: Finances2024Schema["Breakdown"][];
    /** @description Additional Information about the item. */
    contexts?: Finances2024Schema["Contexts"];
  };
  /**
   * @description Related business identifiers of the item.
   * @example {
   *   "itemRelatedIdentifierName": "ORDER_ADJUSTMENT_ITEM_ID",
   *   "itemRelatedIdentifierValue": "OAI-123456789"
   * }
   */
  ItemRelatedIdentifier: {
    /**
     * @description Enumerated set of related item identifier names for the item.
     * @enum {string}
     */
    itemRelatedIdentifierName?:
      | "ORDER_ADJUSTMENT_ITEM_ID"
      | "COUPON_ID"
      | "REMOVAL_SHIPMENT_ITEM_ID"
      | "TRANSACTION_ID";
    /** @description Corresponding value to `ItemRelatedIdentifierName`. */
    itemRelatedIdentifierValue?: string;
  };
  /** @description Related business identifiers of the item in the transaction. */
  ItemRelatedIdentifiers: Finances2024Schema["ItemRelatedIdentifier"][];
  /**
   * @description A list of breakdowns that detail how the total amount is calculated for the transaction.
   * @example [
   *   {
   *     "breakdownType": "Sales",
   *     "breakdownAmount": {
   *       "currencyAmount": 10,
   *       "currencyCode": "USD"
   *     },
   *     "breakdowns": [
   *       {
   *         "breakdownType": "Product Charges",
   *         "breakdownAmount": {
   *           "currencyAmount": 10,
   *           "currencyCode": "USD"
   *         },
   *         "breakdowns": []
   *       }
   *     ]
   *   }
   * ]
   */
  Breakdowns: Finances2024Schema["Breakdown"][];
  /** @description Details about the movement of money in the financial transaction. Breakdowns are further categorized into breakdown types, breakdown amounts, and further breakdowns. */
  Breakdown: {
    /** @description The type of charge. */
    breakdownType?: string;
    /** @description The monetary amount of the charge. */
    breakdownAmount?: Finances2024Schema["Currency"];
    /** @description A list of breakdowns that detail how the total amount is calculated for the transaction. */
    breakdowns?: Finances2024Schema["Breakdown"][];
  };
  /** @description A list of additional information about the item. */
  Contexts: Finances2024Schema["Context"][];
  /** @description Additional Information about the item. */
  Context: {
    contextType: string;
  } & Finances2024Schema["AmazonPayContext"] &
    Finances2024Schema["ProductContext"] &
    Finances2024Schema["PaymentsContext"] &
    Finances2024Schema["DeferredContext"] &
    Finances2024Schema["BusinessContext"] &
    Finances2024Schema["TimeRangeContext"];
  /**
   * @description Additional information related to the product.
   * @example {
   *   "asin": "B07FGXZQZ1",
   *   "sku": "sku-12",
   *   "quantityShipped": 1,
   *   "fulfillmentNetwork": "MFN"
   * }
   */
  ProductContext: {
    /** @description The Amazon Standard Identification Number (ASIN) of the item. */
    asin?: string;
    /** @description The Stock Keeping Unit (SKU) of the item. */
    sku?: string;
    /**
     * Format: int32
     * @description The quantity of the item shipped.
     */
    quantityShipped?: number;
    /** @description The fulfillment network of the item. */
    fulfillmentNetwork?: string;
  };
  /**
   * @description Additional information related to Amazon Pay.
   * @example {
   *   "storeName": "Store 1",
   *   "orderType": "Order Type",
   *   "channel": "MFN"
   * }
   */
  AmazonPayContext: {
    /** @description The name of the store that is related to the transaction. */
    storeName?: string;
    /** @description The transaction's order type. */
    orderType?: string;
    /** @description Channel details of related transaction. */
    channel?: string;
  };
  /**
   * @description Additional information related to payments-related transactions.
   * @example {
   *   "paymentType": "Debit Card",
   *   "paymentMethod": "BANK",
   *   "paymentReference": "XXXXX123",
   *   "paymentDate": "2020-07-14T03:35:13.214Z"
   * }
   */
  PaymentsContext: {
    /** @description The type of payment. */
    paymentType?: string;
    /** @description The method of payment. */
    paymentMethod?: string;
    /** @description The reference number of the payment. */
    paymentReference?: string;
    /** @description The date of the payment. */
    paymentDate?: Finances2024Schema["Date"];
  };
  /**
   * @description Additional information related to deferred transactions.
   * @example {
   *   "deferralReason": "B2B",
   *   "maturityDate": "2024-07-14T00:00:00Z"
   * }
   */
  DeferredContext: {
    /**
     * @description The deferral policy applied to the transaction.
     *
     * **Examples:** `B2B` (invoiced orders), `DD7` (delivery date policy)
     */
    deferralReason?: string;
    /** @description The release date of the transaction. */
    maturityDate?: Finances2024Schema["Date"];
  };
  /**
   * @description Information about the line of business associated with a transaction.
   * @example {
   *   "storeName": "AMAZON_HAUL"
   * }
   */
  BusinessContext: {
    /**
     * @description The store name associated with the transaction.
     * @enum {string}
     */
    storeName?: "AMAZON_HAUL";
  };
  /**
   * @description Additional information that is related to the time range of the transaction.
   * @example {
   *   "startTime": "2020-07-14T03:35:13.214Z",
   *   "endTime": "2020-07-14T03:35:13.214Z"
   * }
   */
  TimeRangeContext: {
    /** @description The start time of the transaction. */
    startTime?: Finances2024Schema["Date"];
    /** @description The end time of the transaction. */
    endTime?: Finances2024Schema["Date"];
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: {
    /** @description The error responses that are returned when the request is unsuccessful. */
    errors: Finances2024Schema["Error"][];
  };
  /** @description An error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition. */
    message: string;
    /** @description Additional details that can help the caller understand or fix the issue. */
    details?: string;
  };
}

export interface operations {
  /**
   * Returns transactions for the given parameters. Financial events might not include orders from the last 48 hours.
   *
   * **Usage plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 10 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).
   */
  listTransactions: {
    parameters: {
      query: {
        /**
         * The response includes financial events posted on or after this date. This date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The date-time must be more than two minutes before the time of the request.
         *
         * This field is required if you do not specify a related identifier.
         */
        postedAfter?: string;
        /**
         * The response includes financial events posted before (but not on) this date. This date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
         *
         * The date-time must be later than `PostedAfter` and more than two minutes before the request was submitted. If `PostedAfter` and `PostedBefore` are more than 180 days apart, the response is empty.
         *
         * **Default:** Two minutes before the time of the request.
         */
        postedBefore?: string;
        /** The identifier of the marketplace from which you want to retrieve transactions. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
        marketplaceId?: string;
        /**
         * The status of the transaction.
         *
         * **Possible values:**
         *
         * * `DEFERRED`: the transaction is currently deferred.
         * * `RELEASED`: the transaction is currently released.
         * * `DEFERRED_RELEASED`: the transaction was deferred in the past, but is now released. The status of a deferred transaction is updated to `DEFERRED_RELEASED` when the transaction is released.
         */
        transactionStatus?: string;
        /**
         * The name of the `relatedIdentifier`.
         *
         * **Possible values:**
         *
         * * `FINANCIAL_EVENT_GROUP_ID`: the financial event group ID associated with the transaction.
         *
         * * `ORDER_ID`: the order ID associated with the transaction.
         *
         * **Note:**
         *
         *  FINANCIAL_EVENT_GROUP_ID and ORDER_ID are the only `relatedIdentifier` with filtering capabilities at the moment. While other `relatedIdentifier` values will be included in the response when available, they cannot be used for filtering purposes.
         */
        relatedIdentifierName?: string;
        /** The value of the `relatedIdentifier`. */
        relatedIdentifierValue?: string;
        /** The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages. */
        nextToken?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: Finances2024Schema["ListTransactionsResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: Finances2024Schema["ErrorList"];
      };
    };
  };
}

export interface external {}

export default Finances2024Schema;
