/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/orders/2026-01-01/orders": {
    /**
     * Returns orders created or updated during the time period that you specify. You can filter the response for specific types of orders.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0056 | 20 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may receive higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api) in the Selling Partner API documentation.
     */
    get: operations["searchOrders"];
  };
  "/orders/2026-01-01/orders/{orderId}": {
    /**
     * Returns the order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may receive higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api) in the Selling Partner API documentation.
     */
    get: operations["getOrder"];
  };
}

export interface Orders2026Schema {
  /** @description A list of orders. */
  SearchOrdersResponse: {
    /** @description An array containing all orders that match the search criteria. */
    orders: Orders2026Schema["Order"][];
    /** @description Pagination occurs when a request has results that exceed the response limit. This means the results are divided into individual pages. To retrieve a different page, you must pass the token value as the `paginationToken` query parameter in the subsequent request. All other parameters must be provided with the same values that were provided with the request that generated this token, with the exception of `maxResultsPerPage` and `includedData`, which can be modified between calls. The token will expire after 24 hours. When there are no other pages to fetch, the `pagination` field will be absent from the response. */
    pagination?: Orders2026Schema["Pagination"];
    /**
     * Format: date-time
     * @description Only orders updated before the specified time are returned. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    lastUpdatedBefore?: string;
    /**
     * Format: date-time
     * @description Only orders placed before the specified time are returned. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    createdBefore?: string;
  };
  /** @description Pagination occurs when a request has results that exceed the response limit. This means the results are divided into individual pages. To retrieve a different page, you must pass the token value as the `paginationToken` query parameter in the subsequent request. All other parameters must be provided with the same values that were provided with the request that generated this token, with the exception of `maxResultsPerPage` and `includedData`, which can be modified between calls. The token will expire after 24 hours. When there are no other pages to fetch, the `pagination` field will be absent from the response. */
  Pagination: {
    /** @description A token that can be used to fetch the next page of results. */
    nextToken?: string;
  };
  /** @description Order details. */
  GetOrderResponse: {
    /** @description All available information about the requested order. */
    order: Orders2026Schema["Order"];
  };
  /** @description Comprehensive information about a customer order. */
  Order: {
    /** @description An Amazon-defined order identifier. */
    orderId: string;
    /** @description Alternative identifiers that can be used to reference this order, such as seller-defined order numbers. */
    orderAliases?: Orders2026Schema["Alias"][];
    /**
     * Format: date-time
     * @description The time when the customer placed the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    createdTime: string;
    /**
     * Format: date-time
     * @description The most recent time when any aspect of this order was modified by Amazon or the seller. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    lastUpdatedTime: string;
    /**
     * @description Special programs associated with this order that may affect fulfillment or customer experience.
     *
     * **Possible values**: `AMAZON_BAZAAR`, `AMAZON_BUSINESS`, `AMAZON_EASY_SHIP`, `AMAZON_HAUL`, `DELIVERY_BY_AMAZON`, `FBM_SHIP_PLUS`, `INVOICE_BY_AMAZON`, `IN_STORE_PICK_UP`, `PREMIUM`, `PREORDER`, `PRIME`
     */
    programs?: string[];
    /** @description Other orders that have a direct relationship to this order, such as replacement or exchange orders. */
    associatedOrders?: Orders2026Schema["AssociatedOrder"][];
    /** @description Information about where this order was placed. */
    salesChannel: Orders2026Schema["SalesChannel"];
    /** @description Information about the customer who purchased this order. */
    buyer?: Orders2026Schema["Buyer"];
    /** @description Information about the person or location where this order should be delivered. */
    recipient?: Orders2026Schema["Recipient"];
    /** @description Financial information about this order. */
    proceeds?: Orders2026Schema["OrderProceeds"];
    /** @description Payment information for the order. */
    payment?: Orders2026Schema["OrderPayment"];
    /** @description Tax-related information for the order. */
    tax?: Orders2026Schema["OrderTax"];
    /** @description Information about how this order is being processed and shipped. */
    fulfillment?: Orders2026Schema["OrderFulfillment"];
    /** @description The list of all order items included in this order. */
    orderItems: Orders2026Schema["OrderItem"][];
    /** @description Shipping packages created for this order, including tracking information. **Note:** Only available for merchant-fulfilled (FBM) orders. */
    packages?: Orders2026Schema["OrderPackage"][];
  };
  /** @description An alternative identifier that provides a different way to reference the same order. */
  Alias: {
    /** @description The alternative identifier value that can be used to reference this order. */
    aliasId: string;
    /**
     * @description The kind of alternative identifier this represents.
     *
     * **Possible values**: `SELLER_ORDER_ID`
     */
    aliasType: string;
  };
  /** @description Another order that has a direct business relationship with the current order, such as replacements or exchanges. */
  AssociatedOrder: {
    /** @description The unique identifier of the related order that is associated with the current order. */
    orderId?: string;
    /**
     * @description The relationship between the current order and the associated order.
     *
     * **Possible values**: `REPLACEMENT_ORIGINAL_ID`, `EXCHANGE_ORIGINAL_ID`
     */
    associationType?: string;
  };
  /** @description Information about where the customer placed this order. */
  SalesChannel: {
    /**
     * @description The name of the sales platform or channel where the customer placed this order.
     *
     * **Possible values**: `AMAZON`, `NON_AMAZON`
     */
    channelName: string;
    /** @description The unique identifier for the specific marketplace within the sales channel where this order was placed. */
    marketplaceId?: string;
    /** @description The human-readable name of the marketplace where this order was placed. */
    marketplaceName?: string;
  };
  /** @description Information about the customer who purchased the order. */
  Buyer: {
    /** @description The full name of the customer who placed the order. */
    buyerName?: string;
    /** @description The anonymized email address of the buyer. **Note:** Only available for merchant-fulfilled (FBM) orders. */
    buyerEmail?: string;
    /** @description The name of the company or organization for a business order. */
    buyerCompanyName?: string;
    /** @description The purchase order (PO) number entered by the buyer at checkout. Only returned for orders where the buyer entered a PO number at checkout. */
    buyerPurchaseOrderNumber?: string;
  };
  /** @description Information about the recipient to whom the order should be delivered. */
  Recipient: {
    /** @description The address where the order should be delivered to the customer. */
    deliveryAddress?: Orders2026Schema["CustomerAddress"];
    /** @description Special instructions and preferences that the customer specifies for how the order should be delivered. */
    deliveryPreference?: Orders2026Schema["DeliveryPreference"];
  };
  /** @description The money that the seller receives from the sale of the order. */
  OrderProceeds: {
    /** @description The total amount that the seller receives from the sale of the order. */
    grandTotal?: Orders2026Schema["Money"];
  };
  /** @description Information about how the order is being processed, packed, and shipped to the customer. */
  OrderFulfillment: {
    /** @description The current status of the order in the fulfillment process, from pending to handover to carrier. */
    fulfillmentStatus: Orders2026Schema["FulfillmentStatus"];
    /**
     * @description Specifies whether Amazon or the merchant is responsible for fulfilling this order.
     *
     * **Possible values**: `AMAZON`, `MERCHANT`.
     */
    fulfilledBy?: string;
    /**
     * @description The category of the shipping speed option selected by the customer at checkout.
     *
     * **Possible values**: `EXPEDITED`, `FREE_ECONOMY`, `NEXT_DAY`, `PRIORITY`, `SAME_DAY`, `SECOND_DAY`, `SCHEDULED`, `STANDARD`.
     */
    fulfillmentServiceLevel?: string;
    /** @description The promised time period within which the order must be shipped to meet the customer's delivery expectations. */
    shipByWindow?: Orders2026Schema["DateTimeRange"];
    /** @description The promised time period within which the order should be delivered to the customer. */
    deliverByWindow?: Orders2026Schema["DateTimeRange"];
  };
  /** @description Information about a single product within an order. */
  OrderItem: {
    /** @description A unique identifier for this specific item within the order. */
    orderItemId: string;
    /** @description The number of units of this item that the customer ordered. */
    quantityOrdered: number;
    /** @description The unit of measure and value for items sold by weight, volume, or other measurements rather than simple count. */
    measurement?: Orders2026Schema["Measurement"];
    /** @description A list of order items associated with this item. For example, a value-add service purchased with the product. */
    associatedOrderItems?: Orders2026Schema["AssociatedOrderItem"][];
    /**
     * @description Special programs that apply specifically to this item within the order.
     *
     * **Possible values**: `TRANSPARENCY`, `SUBSCRIBE_AND_SAVE`
     */
    programs?: string[];
    /** @description Information about the product being ordered. */
    product: Orders2026Schema["ItemProduct"];
    /** @description The money that the seller receives from the sale of this specific item. */
    proceeds?: Orders2026Schema["ItemProceeds"];
    /** @description The expense information related to this specific item. */
    expense?: Orders2026Schema["ItemExpense"];
    /** @description Details about any discounts, coupons, or promotional offers applied to this item. */
    promotion?: Orders2026Schema["ItemPromotion"];
    /** @description The cancellation information of the order item. */
    cancellation?: Orders2026Schema["ItemCancellation"];
    /** @description Information about how the order item should be processed, packed, and shipped to the customer. */
    fulfillment?: Orders2026Schema["ItemFulfillment"];
    /** @description Tax-related information for this order item. */
    tax?: Orders2026Schema["ItemTax"];
  };
  /** @description Information about a physical shipping package, including tracking details. **Note:** Only available for merchant-fulfilled (FBM) orders. */
  OrderPackage: {
    /** @description A unique identifier for this package within the context of the order. */
    packageReferenceId: string;
    /**
     * Format: date-time
     * @description The exact time when this shipping package was created and prepared for shipment. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    createdTime?: string;
    /** @description The current status of this package. */
    packageStatus?: Orders2026Schema["PackageStatus"];
    /** @description The carrier responsible for transporting this package to the customer. */
    carrier?: string;
    /**
     * Format: date-time
     * @description The exact time when this package was handed over to the carrier and began its journey to the customer. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    shipTime?: string;
    /** @description The specific shipping method or service used for delivering this package. */
    shippingService?: string;
    /** @description The carrier-provided tracking number that customers can use to monitor the package's delivery progress. */
    trackingNumber?: string;
    /** @description The physical address from which this package was shipped, typically the merchant's warehouse or fulfillment center. */
    shipFromAddress?: Orders2026Schema["MerchantAddress"];
    /** @description A list of all order items included in this specific package. */
    packageItems?: Orders2026Schema["PackageItem"][];
  };
  /** @description Contains all delivery instructions that the customer provides for the shipping address. */
  DeliveryPreference: {
    /** @description The drop-off location selected by the customer. */
    dropOffLocation?: string;
    /** @description Building instructions, nearby landmark, or navigation instructions. */
    addressInstruction?: string;
    /** @description Business hours and days when the delivery is preferred. */
    deliveryTime?: Orders2026Schema["PreferredDeliveryTime"];
    /** @description A list of miscellaneous delivery capabilities associated with the shipping address. */
    deliveryCapabilities?: Orders2026Schema["PreferredDeliveryCapability"][];
  };
  /** @description The physical address of the customer. */
  CustomerAddress: {
    /** @description The full name of the person who will receive the delivery at this address. */
    name?: string;
    /** @description The name of the business or organization at this address. */
    companyName?: string;
    /** @description The primary street address. */
    addressLine1?: string;
    /** @description Additional address information. */
    addressLine2?: string;
    /** @description Additional address information. */
    addressLine3?: string;
    /** @description The city of the address. */
    city?: string;
    /** @description The district or county of the address. */
    districtOrCounty?: string;
    /** @description The state, province, or region of the address. */
    stateOrRegion?: string;
    /** @description The municipality of the address. */
    municipality?: string;
    /** @description The postal code, ZIP code, or equivalent mailing code of the address. */
    postalCode?: string;
    /** @description The two-letter country code identifying the country of the address, in ISO 3166-1 format. */
    countryCode?: string;
    /**
     * @description The contact phone number for delivery coordination and customer communication.
     *
     * **Note**: The buyer phone number will be suppressed in some cases, including but not limited to:
     *
     * - All FBA (Fulfillment by Amazon) orders.
     * - Shipped FBM (Fulfilled by the merchant) orders when current date is past the latest delivery date.
     */
    phone?: string;
    /**
     * @description Additional address components specific to certain countries that provide more detailed location information.
     *
     * **Note**: Only available with Brazil shipping addresses.
     */
    extendedFields?: Orders2026Schema["AddressExtendedFields"];
    /**
     * @description The type of location.
     *
     * **Possible values**: `RESIDENTIAL`, `COMMERCIAL`, `PICKUP_POINT`
     */
    addressType?: string;
  };
  /**
   * @description Additional address components that provide more detailed location information, helping with precise delivery routing.
   *
   * **Note**: Only available with Brazil shipping addresses.
   */
  AddressExtendedFields: {
    /** @description The name of the street. */
    streetName?: string;
    /** @description The house, building, or property number associated with the location's street address. */
    streetNumber?: string;
    /** @description The floor number / unit number. */
    complement?: string;
    /** @description The neighborhood. This value is only used in some countries (such as Brazil). */
    neighborhood?: string;
  };
  /** @description The physical address of the merchant. */
  MerchantAddress: {
    /** @description The name of the business or facility at this address. */
    name?: string;
    /** @description The primary street address of the merchant's location. */
    addressLine1?: string;
    /** @description Additional address information. */
    addressLine2?: string;
    /** @description Additional address information. */
    addressLine3?: string;
    /** @description The city of the address. */
    city?: string;
    /** @description The district or county of the address. */
    districtOrCounty?: string;
    /** @description The state, province, or region of the address. */
    stateOrRegion?: string;
    /** @description The municipality of the address. */
    municipality?: string;
    /** @description The postal code or ZIP code of the address. */
    postalCode?: string;
    /** @description The two-letter country code for the address, in ISO 3166-1 format. */
    countryCode?: string;
  };
  /**
   * @description The current fulfillment status of an order, indicating where the order is in the fulfillment process from placement to handover to carrier.
   * @enum {string}
   */
  FulfillmentStatus:
    | "PENDING_AVAILABILITY"
    | "PENDING"
    | "UNSHIPPED"
    | "PARTIALLY_SHIPPED"
    | "SHIPPED"
    | "CANCELLED"
    | "UNFULFILLABLE";
  /** @description Specifies the unit of measure and quantity for items that are sold by weight, volume, length, or other measurements rather than simple count. */
  Measurement: {
    /**
     * @description The specific unit of measurement used to quantify this item.
     * @enum {string}
     */
    unit:
      | "OUNCES"
      | "POUNDS"
      | "KILOGRAMS"
      | "GRAMS"
      | "MILLIGRAMS"
      | "INCHES"
      | "FEET"
      | "METERS"
      | "CENTIMETERS"
      | "MILLIMETERS"
      | "SQUARE_METERS"
      | "SQUARE_CENTIMETERS"
      | "SQUARE_FEET"
      | "SQUARE_INCHES"
      | "GALLONS"
      | "PINTS"
      | "QUARTS"
      | "FLUID_OUNCES"
      | "LITERS"
      | "CUBIC_METERS"
      | "CUBIC_FEET"
      | "CUBIC_INCHES"
      | "CUBIC_CENTIMETERS"
      | "COUNT";
    /** @description The numerical quantity or amount being measured in the specified unit. */
    value: number;
  };
  /** @description Product information for an order item. */
  ItemProduct: {
    /** @description The Amazon Standard Identification Number (ASIN) of the item. */
    asin?: Orders2026Schema["Asin"];
    /** @description The product name or title as displayed to customers in the marketplace. */
    title?: string;
    /** @description The item's seller stock keeping unit (SKU). */
    sellerSku?: Orders2026Schema["SKU"];
    /** @description Information about the physical condition and quality of the item being sold. */
    condition?: Orders2026Schema["ItemCondition"];
    /** @description Pricing information for this product. */
    price?: Orders2026Schema["ItemPrice"];
    /** @description Unique serial numbers for products that require individual tracking, typically provided for FBA orders. */
    serialNumbers?: string[];
    /** @description Information about any personalization or customization applied to this product. */
    customization?: Orders2026Schema["ItemCustomization"];
  };
  /** @description The money that the seller receives from the sale of this specific item. */
  ItemProceeds: {
    /** @description The total monetary amount for this order item. */
    proceedsTotal?: Orders2026Schema["Money"];
    /** @description The breakdown of proceeds. */
    breakdowns?: Orders2026Schema["ItemProceedsBreakdown"][];
  };
  /** @description The expense information related to this specific item. */
  ItemExpense: {
    /** @description The cost of points. */
    pointsCost?: Orders2026Schema["ItemPointsCost"];
  };
  /** @description Details about any discounts, coupons, or promotional offers applied to this item. */
  ItemPromotion: {
    /** @description A list of promotions applied to the order item. */
    breakdowns?: Orders2026Schema["ItemPromotionBreakdown"][];
  };
  /** @description The cancellation information of the order item. */
  ItemCancellation: {
    /** @description Details of the cancellation request submitted for this order item. */
    cancellationRequest?: Orders2026Schema["ItemCancellationRequest"];
  };
  /** @description Information about how the order item should be processed, packed, and shipped to the customer. */
  ItemFulfillment: {
    /** @description The number of units of this item that have been successfully processed and shipped. */
    quantityFulfilled?: number;
    /** @description The number of units of this item that remain to be processed and shipped. */
    quantityUnfulfilled?: number;
    /** @description Information related to the warehouse picking process for this item. */
    picking?: Orders2026Schema["ItemPicking"];
    /** @description Information related to the packaging process for this item. */
    packing?: Orders2026Schema["ItemPacking"];
    /** @description Information related to the shipping and delivery process for this item. */
    shipping?: Orders2026Schema["ItemShipping"];
  };
  /** @description Customer-specified time preferences for when deliveries should be attempted at the destination address. */
  PreferredDeliveryTime: {
    /** @description Business hours when the business is open for deliveries. */
    businessHours?: Orders2026Schema["BusinessHour"][];
    /** @description Specific dates within the next 30 days when normal business hours do not apply. */
    exceptionDates?: Orders2026Schema["ExceptionDate"][];
  };
  /** @description Business days and hours when the destination is open for deliveries. */
  BusinessHour: {
    /**
     * @description Specific day of the week for which operating hours are being defined.
     * @enum {string}
     */
    dayOfWeek?: "SUN" | "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT";
    /** @description Collection of time windows during which the location is available for deliveries on the specified day. */
    timeWindows?: Orders2026Schema["TimeWindow"][];
  };
  /** @description Special dates when normal business hours are modified or suspended, requiring different delivery scheduling. */
  ExceptionDate: {
    /**
     * Format: date
     * @description Specific calendar date when normal operating hours do not apply. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format at day granularity.
     */
    exceptionDate?: string;
    /**
     * @description Operational status of the business on the specified exception date.
     * @enum {string}
     */
    exceptionDateType?: "CLOSED" | "OPEN";
    /** @description Alternative operating hours that apply specifically to this exception date. */
    timeWindows?: Orders2026Schema["TimeWindow"][];
  };
  /** @description Specific time interval defining the start and end times. */
  TimeWindow: {
    /** @description The beginning of the time window. */
    startTime?: Orders2026Schema["HourMinute"];
    /** @description The end of the time window. */
    endTime?: Orders2026Schema["HourMinute"];
  };
  /** @description The time when the business opens or closes. */
  HourMinute: {
    /** @description The hour when the business opens or closes, in 24-hour format (0-23). */
    hour?: number;
    /** @description The minute when the business opens or closes. */
    minute?: number;
  };
  /**
   * @description Special delivery capabilities available at the shipping address that may affect delivery options and methods.
   *
   * **Possible values**:
   * - `HAS_ACCESS_POINT` (Delivery location includes designated pickup or drop-off access points)
   * - `PALLET_ENABLED` (Address is equipped to receive large pallet deliveries)
   * - `PALLET_DISABLED` (Address cannot accommodate pallet delivery methods)
   */
  PreferredDeliveryCapability: string;
  /** @description Detailed information about the physical condition and quality state of the item being sold. */
  ItemCondition: {
    /**
     * @description The primary condition category that broadly describes the item's state.
     *
     * **Possible values**: `NEW`, `USED`, `COLLECTIBLE`, `REFURBISHED`, `PREORDER`, `CLUB`.
     */
    conditionType?: string;
    /**
     * @description A more specific condition classification that provides additional detail about the item's quality within the main condition type.
     *
     * **Possible values**: `NEW`, `MINT`, `VERY_GOOD`, `GOOD`, `ACCEPTABLE`, `POOR`, `CLUB`, `OEM`, `WARRANTY`, `REFURBISHED_WARRANTY`, `REFURBISHED`, `OPEN_BOX`, `ANY`, `OTHER`.
     */
    conditionSubtype?: string;
    /** @description Additional details provided by the seller to describe the specific condition of this particular item. */
    conditionNote?: string;
  };
  /** @description Pricing information for the order item. */
  ItemPrice: {
    /** @description The price charged for a single unit of this product, before any quantity-based calculations. */
    unitPrice?: Orders2026Schema["Money"];
    /**
     * @description Indicates that the selling price is a special price that is only available for Amazon Business orders. For more information about the Amazon Business Seller Program, refer to the [Amazon Business website](https://www.amazon.com/b2b/info/amazon-business).
     *
     * **Possible value**: `BUSINESS_PRICE`
     */
    priceDesignation?: string;
  };
  /** @description Information about any personalization, customization, or special modifications applied to this order item. */
  ItemCustomization: {
    /** @description The URL of the customized data for custom orders from the Amazon Custom program. */
    customizedUrl?: string;
  };
  /** @description Detailed proceeds breakdown for a specific order item. */
  ItemProceedsBreakdown: {
    /**
     * @description Category classification of the proceeds breakdown.
     *
     * **Possible values**: `ITEM`, `SHIPPING`, `GIFT_WRAP`, `COD_FEE`, `OTHER`, `TAX`, `DISCOUNT`
     */
    type?: string;
    /** @description Monetary amount for the proceeds breakdown. */
    subtotal?: Orders2026Schema["Money"];
    /** @description Further granular breakdown of the subtotal. */
    detailedBreakdowns?: Orders2026Schema["ItemProceedsDetailedBreakdown"][];
  };
  /** @description Further granular breakdown of the subtotal of the proceeds breakdown, only available for TAX and DISCOUNT proceeds types. */
  ItemProceedsDetailedBreakdown: {
    /**
     * @description Specific classification of the further granular breakdown.
     *
     * **Possible values**: `ITEM`, `SHIPPING`, `GIFT_WRAP`, `COD_FEE`, `OTHER`, `DISCOUNT`
     */
    subtype?: string;
    /** @description Monetary amount for the further granular breakdown. */
    value?: Orders2026Schema["Money"];
  };
  /** @description Information about Amazon Points granted with the purchase of an item, including both quantity and monetary equivalent value. */
  ItemPointsCost: {
    /** @description Details of the Amazon Points granted, including count and monetary value. */
    pointsGranted?: Orders2026Schema["PointsGranted"];
  };
  /** @description Information about Amazon Points awarded with an item purchase. */
  PointsGranted: {
    /** @description Total number of Amazon Points granted to the customer's account for this item purchase. */
    pointsNumber?: number;
    /** @description Cash equivalent value of the awarded Amazon Points. */
    pointsMonetaryValue?: Orders2026Schema["Money"];
  };
  /** @description Detailed information about a specific promotional offer applied to an order item. */
  ItemPromotionBreakdown: {
    /** @description Unique identifier for the promotion applied to this item. */
    promotionId?: string;
  };
  /** @description Detailed information about a cancellation request submitted for a specific order item. */
  ItemCancellationRequest: {
    /**
     * @description Entity that initiated the cancellation request for this item.
     *
     * **Possible values**: `BUYER`
     */
    requester?: string;
    /** @description Explanation provided for why the cancellation was requested. */
    cancelReason?: string;
  };
  /** @description Information related to the warehouse picking process for an order item. */
  ItemPicking: {
    /** @description Substitution preference for an order item when it becomes unavailable during fulfillment. */
    substitutionPreference?: Orders2026Schema["ItemSubstitutionPreference"];
  };
  /**
   * @description Information related to the packaging process for an order item.
   * @example {
   *   "giftOption": {
   *     "giftMessage": "Happy Holidays! Enjoy your new smart speakers.",
   *     "giftWrapLevel": "PREMIUM"
   *   },
   *   "serialNumberRequirement": {
   *     "requirementType": "REQUIRED"
   *   }
   * }
   */
  ItemPacking: {
    /** @description Gift wrapping and messaging specified for this item. */
    giftOption?: Orders2026Schema["GiftOption"];
    /** @description Whether serial numbers must be provided for this line item. */
    serialNumberRequirement?: Orders2026Schema["SerialNumberRequirement"];
  };
  /** @description Information related to the shipping and delivery process for an order item. */
  ItemShipping: {
    /** @description When this item is expected to be delivered to the customer. */
    scheduledDeliveryWindow?: Orders2026Schema["DateTimeRange"];
    /** @description Special shipping requirements and restrictions that apply to this item. */
    shippingConstraints?: Orders2026Schema["ItemShippingConstraints"];
    /** @description Additional information needed for cross-border delivery of this item. */
    internationalShipping?: Orders2026Schema["ItemInternationalShipping"];
  };
  /** @description Gift wrapping and personalization options selected by the customer for an order item. */
  GiftOption: {
    /** @description Personal message from the buyer to be included with the gift-wrapped item. */
    giftMessage?: string;
    /** @description Type or quality level of gift wrapping service selected by the customer. */
    giftWrapLevel?: string;
  };
  /** @description Whether serial numbers must be provided for this line item. */
  SerialNumberRequirement: {
    /**
     * @description The requirement type for this request.
     *
     * **Possible values**: `REQUIRED`
     */
    requirementType?: string;
  };
  /** @description Substitution preference for an order item when it becomes unavailable during fulfillment. */
  ItemSubstitutionPreference: {
    /**
     * @description Source and nature of the substitution preferences for this item.
     * @enum {string}
     */
    substitutionType:
      | "CUSTOMER_PREFERENCE"
      | "AMAZON_RECOMMENDED"
      | "DO_NOT_SUBSTITUTE";
    /** @description List of alternative products that can be substituted for the original item if it becomes unavailable. */
    substitutionOptions?: Orders2026Schema["ItemSubstitutionOption"][];
  };
  /** @description Alternative product that can be substituted for an original order item when it becomes unavailable during fulfillment. */
  ItemSubstitutionOption: {
    /** @description Amazon Standard Identification Number of the substitute product. */
    asin?: string;
    /** @description Number of units of the substitute item to be selected if substitution occurs. */
    quantityOrdered?: number;
    /** @description The item's seller stock keeping unit (SKU). */
    sellerSku?: string;
    /** @description Product name or title of the substitute item as displayed to customers. */
    title?: string;
    /** @description Unit of measure and quantity specifications for the substitute product. */
    measurement?: Orders2026Schema["Measurement"];
  };
  /** @description Special shipping requirements and restrictions that must be observed when shipping an order item. */
  ItemShippingConstraints: {
    /** @description The line item must be delivered by pallet. */
    palletDelivery?: Orders2026Schema["ConstraintType"];
    /** @description Payment must be collected from the customer at the time of delivery. */
    cashOnDelivery?: Orders2026Schema["ConstraintType"];
    /** @description The recipient of the line item must sign to confirm its delivery. */
    signatureConfirmation?: Orders2026Schema["ConstraintType"];
    /** @description The person receiving the line item must be the same as the intended recipient of the order. */
    recipientIdentityVerification?: Orders2026Schema["ConstraintType"];
    /** @description The carrier must confirm that the recipient is of the legal age to receive the line item upon delivery. */
    recipientAgeVerification?: Orders2026Schema["ConstraintType"];
  };
  /**
   * @description Classification of the enforcement level required for shipping and delivery constraints.
   * @enum {string}
   */
  ConstraintType: "MANDATORY";
  /** @description Additional requirements needed for cross-border shipping of an order item. */
  ItemInternationalShipping: {
    /** @description Import One-Stop Shop registration number required for EU VAT compliance when shipping from outside the European Union. Sellers shipping to the EU from outside the EU must provide this IOSS number to their carrier when Amazon has collected the VAT on the sale. */
    iossNumber?: string;
  };
  /** @description Current status and detailed tracking information for a shipping package throughout the delivery process. */
  PackageStatus: {
    /**
     * @description Primary status classification of the package in the shipping workflow.
     * @enum {string}
     */
    status:
      | "PENDING"
      | "IN_TRANSIT"
      | "SHIPPED"
      | "DELIVERED"
      | "CANCELLED"
      | "UNDELIVERABLE";
    /**
     * @description Granular status information providing specific details about the package's current location and handling stage.
     *
     * **Possible values**:
     * - `PENDING_SCHEDULE` (Package awaiting pickup scheduling)
     * - `PENDING_PICK_UP` (Package ready for carrier collection from seller)
     * - `PENDING_DROP_OFF` (Package awaiting seller delivery to carrier)
     * - `LABEL_CANCELLED` (Shipping label canceled by seller)
     * - `PICKED_UP` (Package collected by carrier from seller location)
     * - `DROPPED_OFF` (Package delivered to carrier by seller)
     * - `AT_ORIGIN_FC` (Package at originating fulfillment center)
     * - `AT_DESTINATION_FC` (Package at destination fulfillment center)
     * - `DELIVERED` (Package successfully delivered to recipient)
     * - `REJECTED_BY_BUYER` (Package refused by intended recipient)
     * - `UNDELIVERABLE` (Package cannot be delivered due to address or access issues)
     * - `RETURNING_TO_SELLER` (Package in transit back to seller)
     * - `RETURNED_TO_SELLER` (Package successfully returned to seller)
     * - `LOST` (Package location unknown or confirmed lost)
     * - `OUT_FOR_DELIVERY` (Package on delivery vehicle for final delivery)
     * - `DAMAGED` (Package damaged during transit)
     */
    detailedStatus?: string;
  };
  /** @description Individual order item contained within a shipping package. */
  PackageItem: {
    /** @description Unique identifier of the order item included in this package. */
    orderItemId: string;
    /** @description Number of units of this item included in the package shipment. */
    quantity: number;
    /** @description The transparency codes associated with this item for product authentication. */
    transparencyCodes?: string[];
  };
  /** @description Payment information about the order. */
  OrderPayment: {
    /** @description A list of payment executions for the order. */
    paymentExecutions?: Orders2026Schema["PaymentExecution"][];
  };
  /** @description Payment execution details for an order. */
  PaymentExecution: {
    /** @description The payment method used for this payment execution (for example, CashOnDelivery, ConvenienceStore, CreditCard, Invoice, Pix, and so on). */
    paymentMethod?: string;
    /** @description The monetary value of the payment execution. */
    paymentAmount?: Orders2026Schema["Money"];
    /**
     * @description The unique identifier of the payment processor or acquiring bank that authorizes the payment.
     *
     * **Note**: This attribute is only available for orders in the Brazil (BR) marketplace when the `paymentMethod` is `CreditCard` or `Pix`.
     */
    acquirerId?: string;
    /**
     * @description The card network or brand used in the payment transaction (for example, Visa or Mastercard).
     *
     * **Note**: This attribute is only available for orders in the Brazil (BR) marketplace when the `paymentMethod` is `CreditCard`.
     */
    cardBrand?: string;
    /**
     * @description The unique code that confirms the payment authorization.
     *
     * **Note**: This attribute is only available for orders in the Brazil (BR) marketplace when the `paymentMethod` is `CreditCard` or `Pix`.
     */
    authorizationCode?: string;
  };
  /** @description Tax information about the order. */
  OrderTax: {
    /** @description A list of tax registrations associated with the order. */
    taxRegistrations?: Orders2026Schema["OrderTaxRegistration"][];
    /** @description Tax invoicing information for the order. */
    taxInvoicing?: Orders2026Schema["OrderTaxInvoicing"];
  };
  /** @description Tax registration information for an entity associated with the order. */
  OrderTaxRegistration: {
    /**
     * @description The type of entity that the tax registration belongs to.
     *
     * **Possible values**:
     * - `BUYER` (Indicates that this is the buyer's tax registration information)
     * - `MERCHANT` (Indicates that this is the merchant's tax registration information)
     * - `MARKETPLACE` (Indicates that this is the marketplace's tax registration information)
     */
    entityType?: string;
    /** @description The legal name associated with the tax registration. */
    legalName?: string;
    /**
     * @description The type of the tax registration number.
     *
     * **Possible values**: `BUSINESS`, `VAT`, `CST`, `CPF`, `CNPJ`
     */
    taxRegistrationType?: string;
    /** @description The tax registration number that identifies the entity for tax purposes. */
    taxRegistrationNumber?: string;
    /** @description The address associated with the tax registration. */
    taxRegistrationAddress?: Orders2026Schema["CustomerAddress"];
    /** @description Additional attributes related to the tax registration. */
    taxRegistrationAttributes?: Orders2026Schema["TaxRegistrationAttribute"][];
  };
  /** @description An additional attribute associated with a tax registration. */
  TaxRegistrationAttribute: {
    /**
     * @description The name of the tax registration attribute.
     *
     * **Possible values**: `TAX_OFFICE`
     */
    key?: string;
    /** @description The value of the tax registration attribute. */
    value?: string;
  };
  /** @description Tax invoicing information for the order. */
  OrderTaxInvoicing: {
    /**
     * @description The buyer's invoicing preference, which indicates whether the seller should issue an individual or a business invoice to the buyer.
     *
     *  **Note**: This attribute is only available in the Turkey marketplace.
     *
     * **Possible values**:
     * - `INDIVIDUAL` (Issues an individual invoice to the buyer)
     * - `BUSINESS` (Issues a business invoice to the buyer)
     */
    buyerInvoicePreference?: string;
    /**
     * @description The status of the invoice. Only available for Easy Ship orders and orders in the Brazil marketplace.
     *
     * **Possible values**:
     * - `NOT_REQUIRED` (The order does not require an electronic invoice to be uploaded)
     * - `NOT_FOUND` (The order requires an electronic invoice but it is not uploaded)
     * - `PROCESSING` (The required electronic invoice was uploaded and is processing)
     * - `ERRORED` (The uploaded electronic invoice was not accepted)
     * - `ACCEPTED` (The uploaded electronic invoice was accepted)
     */
    invoiceStatus?: string;
  };
  /**
   * @description An associated order item that a customer has purchased with the product. For example, a tire installation service purchased with tires.
   * @example {
   *   "orderId": "123-4567890-7654321",
   *   "orderItemId": "12345678904321",
   *   "associationType": "VALUE_ADD_SERVICE"
   * }
   */
  AssociatedOrderItem: {
    /** @description The order identifier of the associated order item. */
    orderId?: string;
    /** @description The order item identifier of the associated order item. */
    orderItemId?: string;
    /**
     * @description The type of association between the order items.
     *
     * **Possible values**:
     * - `VALUE_ADD_SERVICE` (The associated item is a service order)
     */
    associationType?: string;
  };
  /** @description Tax information for an order item. */
  ItemTax: {
    /** @description A list of tax calculation breakdowns for the order item. */
    taxCalculationBreakdowns?: Orders2026Schema["ItemTaxCalculationBreakdown"][];
    /** @description A list of tax collections for the order item. */
    taxCollections?: Orders2026Schema["ItemTaxCollection"][];
  };
  /** @description Tax calculation breakdowns for an order item. */
  ItemTaxCalculationBreakdown: {
    /**
     * @description The tax reporting scheme applied to this order item.
     *
     * **Possible values**:
     * - `UOSS` (Union one stop shop. The item being purchased is held in the EU for shipment)
     * - `IOSS` (Import one stop shop. The item being purchased is not held in the EU for shipment)
     */
    reportingScheme?: string;
  };
  /** @description Tax collection information for an order item. */
  ItemTaxCollection: {
    /**
     * @description The tax collection model applied to the item.
     *
     * **Possible values**:
     * - `MARKETPLACE_FACILITATOR` (Tax is withheld and remitted to the taxing authority by Amazon on behalf of the seller)
     */
    model?: string;
    /** @description The party responsible for withholding the taxes and remitting them to the taxing authority. */
    responsibleParty?: string;
  };
  /** @description The Amazon Standard Identification Number (ASIN), which uniquely identifies a product (catalog item). */
  Asin: string;
  /** @description The seller SKU of a product (catalog item). This is a unique number assigned by the seller when listing an item. */
  SKU: string;
  /** @description An amount of money, including units in the form of currency. */
  Money: {
    amount: Orders2026Schema["Decimal"];
    /** @description The three-letter currency code that identifies the currency type, following ISO 4217 international standards. */
    currencyCode: string;
  };
  /** @description A decimal number with no loss of precision. Follows RFC 7159 for number representation. */
  Decimal: string;
  /** @description A time period with start and end boundaries. */
  DateTimeRange: {
    /**
     * Format: date-time
     * @description The beginning of the time period, in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    earliestDateTime?: string;
    /**
     * Format: date-time
     * @description The end of the time period, in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    latestDateTime?: string;
  };
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition. */
    message: string;
    /** @description Additional details that can help the caller understand or fix the issue. */
    details?: string;
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: {
    /** @description A list of errors. */
    errors: Orders2026Schema["Error"][];
  };
}

export interface operations {
  /**
   * Returns orders created or updated during the time period that you specify. You can filter the response for specific types of orders.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0056 | 20 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may receive higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api) in the Selling Partner API documentation.
   */
  searchOrders: {
    parameters: {
      query: {
        /**
         * The response includes orders created at or after this time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: You must provide exactly one of `createdAfter` and `lastUpdatedAfter` in your request. If `createdAfter` is provided, neither `lastUpdatedAfter` nor `lastUpdatedBefore` may be provided.
         */
        createdAfter?: string;
        /**
         * The response includes orders created at or before this time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: If you include `createdAfter` in the request, `createdBefore` is optional, and if provided must be equal to or after the `createdAfter` date and at least two minutes before the time of the request. If `createdBefore` is provided, neither `lastUpdatedAfter` nor `lastUpdatedBefore` may be provided.
         */
        createdBefore?: string;
        /**
         * The response includes orders updated at or after this time. An update is any change made by Amazon or the seller, including changes to order status. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: You must provide exactly one of `createdAfter` and `lastUpdatedAfter`. If `lastUpdatedAfter` is provided, neither `createdAfter` nor `createdBefore` may be provided.
         */
        lastUpdatedAfter?: string;
        /**
         * The response includes orders updated at or before this time. An update is any change made by Amazon or the seller, including changes to order status. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: If you include `lastUpdatedAfter` in the request, `lastUpdatedBefore` is optional, and if provided must be equal to or after the `lastUpdatedAfter` date and at least two minutes before the time of the request. If `lastUpdatedBefore` is provided, neither `createdAfter` nor `createdBefore` may be provided.
         */
        lastUpdatedBefore?: string;
        /** A list of `FulfillmentStatus` values you can use to filter the results. */
        fulfillmentStatuses?: (
          | "PENDING_AVAILABILITY"
          | "PENDING"
          | "UNSHIPPED"
          | "PARTIALLY_SHIPPED"
          | "SHIPPED"
          | "CANCELLED"
          | "UNFULFILLABLE"
        )[];
        /**
         * The response includes orders that were placed in marketplaces you include in this list.
         *
         * Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) for a complete list of `marketplaceId` values.
         */
        marketplaceIds?: string[];
        /** The response includes orders that are fulfilled by the parties that you include in this list. */
        fulfilledBy?: ("MERCHANT" | "AMAZON")[];
        /** The maximum number of orders that can be returned per page. The value must be between 1 and 100. **Default:** 100. */
        maxResultsPerPage?: number;
        /** Pagination occurs when a request produces a response that exceeds the `maxResultsPerPage`. This means that the response is divided into individual pages. To retrieve the next page, you must pass the `nextToken` value as the `paginationToken` query parameter in the next request. You will not receive a `nextToken` value on the last page. */
        paginationToken?: string;
        /** A list of datasets to include in the response. */
        includedData?: (
          | "BUYER"
          | "RECIPIENT"
          | "PROCEEDS"
          | "EXPENSE"
          | "PROMOTION"
          | "CANCELLATION"
          | "FULFILLMENT"
          | "PACKAGES"
          | "TAX"
          | "PAYMENT"
        )[];
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: Orders2026Schema["SearchOrdersResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
    };
  };
  /**
   * Returns the order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may receive higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api) in the Selling Partner API documentation.
   */
  getOrder: {
    parameters: {
      path: {
        /** An Amazon-defined order identifier. */
        orderId: string;
      };
      query: {
        /** A list of datasets to include in the response. */
        includedData?: (
          | "BUYER"
          | "RECIPIENT"
          | "PROCEEDS"
          | "EXPENSE"
          | "PROMOTION"
          | "CANCELLATION"
          | "FULFILLMENT"
          | "PACKAGES"
          | "TAX"
          | "PAYMENT"
        )[];
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: Orders2026Schema["GetOrderResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: Orders2026Schema["ErrorList"];
      };
    };
  };
}

export interface external {}

export default Orders2026Schema;
