/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/orders/v0/orders": {
    /**
     * Returns orders that are created or updated during the specified time period. If you want to return specific types of orders, you can apply filters to your request. `NextToken` doesn't affect any filters that you include in your request; it only impacts the pagination for the filtered orders response.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.0167 | 20 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrders"];
  };
  "/orders/v0/orders/{orderId}": {
    /**
     * Returns the order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrder"];
  };
  "/orders/v0/orders/{orderId}/buyerInfo": {
    /**
     * Returns buyer information for the order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrderBuyerInfo"];
  };
  "/orders/v0/orders/{orderId}/address": {
    /**
     * Returns the shipping address for the order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrderAddress"];
  };
  "/orders/v0/orders/{orderId}/orderItems": {
    /**
     * Returns detailed order item information for the order that you specify. If `NextToken` is provided, it's used to retrieve the next page of order items.
     *
     * __Note__: When an order is in the Pending state (the order has been placed but payment has not been authorized), the getOrderItems operation does not return information about pricing, taxes, shipping charges, gift status or promotions for the order items in the order. After an order leaves the Pending state (this occurs when payment has been authorized) and enters the Unshipped, Partially Shipped, or Shipped state, the getOrderItems operation returns information about pricing, taxes, shipping charges, gift status and promotions for the order items in the order.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrderItems"];
  };
  "/orders/v0/orders/{orderId}/orderItems/buyerInfo": {
    /**
     * Returns buyer information for the order items in the order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrderItemsBuyerInfo"];
  };
  "/orders/v0/orders/{orderId}/shipment": {
    /**
     * Update the shipment status for an order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 5 | 15 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    post: operations["updateShipmentStatus"];
  };
  "/orders/v0/orders/{orderId}/regulatedInfo": {
    /**
     * Returns regulated information for the order that you specify.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getOrderRegulatedInfo"];
    /**
     * Updates (approves or rejects) the verification status of an order containing regulated products.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    patch: operations["updateVerificationStatus"];
  };
  "/orders/v0/orders/{orderId}/shipmentConfirmation": {
    /**
     * Updates the shipment confirmation status for a specified order.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 2 | 10 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    post: operations["confirmShipment"];
  };
}

export interface OrdersV0Schema {
  /** @description The request body for the `updateShipmentStatus` operation. */
  UpdateShipmentStatusRequest: {
    marketplaceId: OrdersV0Schema["MarketplaceId"];
    shipmentStatus: OrdersV0Schema["ShipmentStatus"];
    orderItems?: OrdersV0Schema["OrderItems"];
  };
  /** @description The request body for the `updateVerificationStatus` operation. */
  UpdateVerificationStatusRequest: {
    /** @description The updated values of the `VerificationStatus` field. */
    regulatedOrderVerificationStatus: OrdersV0Schema["UpdateVerificationStatusRequestBody"];
  };
  /** @description The updated values of the `VerificationStatus` field. */
  UpdateVerificationStatusRequestBody: {
    /** @description The new verification status of the order. */
    status?: OrdersV0Schema["VerificationStatus"];
    /** @description The identifier of the order's regulated information reviewer. */
    externalReviewerId: string;
    /** @description The unique identifier of the rejection reason used for rejecting the order's regulated information. Only required if the new status is rejected. */
    rejectionReasonId?: string;
    /** @description Additional information regarding the verification of the order. */
    verificationDetails?: OrdersV0Schema["VerificationDetails"];
  };
  /** @description The unobfuscated marketplace identifier. */
  MarketplaceId: string;
  /**
   * @description The shipment status to apply.
   * @enum {string}
   */
  ShipmentStatus: "ReadyForPickup" | "PickedUp" | "RefusedPickup";
  /** @description For partial shipment status updates, the list of order items and quantities to be updated. */
  OrderItems: {
    /** @description The order item's unique identifier. */
    orderItemId?: string;
    /** @description The quantity for which to update the shipment status. */
    quantity?: number;
  }[];
  /** @description The error response schema for the `UpdateShipmentStatus` operation. */
  UpdateShipmentStatusErrorResponse: {
    /** @description One or more unexpected errors occurred during the `UpdateShipmentStatus` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The error response schema for the `UpdateVerificationStatus` operation. */
  UpdateVerificationStatusErrorResponse: {
    /** @description One or more unexpected errors occurred during the `UpdateVerificationStatus` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrders` operation. */
  GetOrdersResponse: {
    /** @description The payload for the `getOrders` operation. */
    payload?: OrdersV0Schema["OrdersList"];
    /** @description One or more unexpected errors occurred during the `getOrders` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrder` operation. */
  GetOrderResponse: {
    /** @description The payload for the `getOrder` operation. */
    payload?: OrdersV0Schema["Order"];
    /** @description One or more unexpected errors occurred during the `getOrder` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrderBuyerInfo` operation. */
  GetOrderBuyerInfoResponse: {
    /** @description The payload for the `getOrderBuyerInfo` operation. */
    payload?: OrdersV0Schema["OrderBuyerInfo"];
    /** @description One or more unexpected errors occurred during the `getOrderBuyerInfo` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrderRegulatedInfo` operation. */
  GetOrderRegulatedInfoResponse: {
    /** @description The payload for the `getOrderRegulatedInfo` operation. */
    payload?: OrdersV0Schema["OrderRegulatedInfo"];
    /** @description One or more unexpected errors occurred during the `getOrderRegulatedInfo` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrderAddress` operation. */
  GetOrderAddressResponse: {
    /** @description The payload for the `getOrderAddress` operations. */
    payload?: OrdersV0Schema["OrderAddress"];
    /** @description One or more unexpected errors occurred during the `getOrderAddress` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrderItems` operation. */
  GetOrderItemsResponse: {
    /** @description The payload for the `getOrderItems` operation. */
    payload?: OrdersV0Schema["OrderItemsList"];
    /** @description One or more unexpected errors occurred during the `getOrderItems` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description The response schema for the `getOrderItemsBuyerInfo` operation. */
  GetOrderItemsBuyerInfoResponse: {
    /** @description The payload for the `getOrderItemsBuyerInfo` operation. */
    payload?: OrdersV0Schema["OrderItemsBuyerInfoList"];
    /** @description One or more unexpected errors occurred during the `getOrderItemsBuyerInfo` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description A list of orders along with additional information to make subsequent API calls. */
  OrdersList: {
    Orders: OrdersV0Schema["OrderList"];
    /** @description When present and not empty, pass this string token in the next request to return the next response page. */
    NextToken?: string;
    /** @description Use this date to select orders that were last updated before (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. Use [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format for all dates. */
    LastUpdatedBefore?: string;
    /** @description Use this date to select orders created before (or at) a specified time. Only orders placed before the specified time are returned. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. */
    CreatedBefore?: string;
  };
  /** @description A list of orders. */
  OrderList: OrdersV0Schema["Order"][];
  /** @description Order information. */
  Order: {
    /** @description An Amazon-defined order identifier, in 3-7-7 format. */
    AmazonOrderId: string;
    /** @description A seller-defined order identifier. */
    SellerOrderId?: string;
    /** @description The date when the order was created. */
    PurchaseDate: string;
    /**
     * @description The date when the order was last updated.
     *
     * __Note__: `LastUpdateDate` is returned with an incorrect date for orders that were last updated before 2009-04-01.
     */
    LastUpdateDate: string;
    /**
     * @description The current order status.
     * @enum {string}
     */
    OrderStatus:
      | "Pending"
      | "Unshipped"
      | "PartiallyShipped"
      | "Shipped"
      | "Canceled"
      | "Unfulfillable"
      | "InvoiceUnconfirmed"
      | "PendingAvailability";
    /**
     * @description Whether the order was fulfilled by Amazon (`AFN`) or by the seller (`MFN`).
     * @enum {string}
     */
    FulfillmentChannel?: "MFN" | "AFN";
    /** @description The sales channel for the first item in the order. */
    SalesChannel?: string;
    /** @description The order channel for the first item in the order. */
    OrderChannel?: string;
    /** @description The order's shipment service level. */
    ShipServiceLevel?: string;
    /** @description The total charge for this order. */
    OrderTotal?: OrdersV0Schema["Money"];
    /** @description The number of items shipped. */
    NumberOfItemsShipped?: number;
    /** @description The number of items unshipped. */
    NumberOfItemsUnshipped?: number;
    /** @description Information about the sub-payment methods for an order. */
    PaymentExecutionDetail?: OrdersV0Schema["PaymentExecutionDetailItemList"];
    /**
     * @description The payment method for the order. This property is limited to COD and CVS payment methods. Unless you need the specific COD payment information provided by the `PaymentExecutionDetailItem` object, we recommend using the `PaymentMethodDetails` property to get payment method information.
     * @enum {string}
     */
    PaymentMethod?: "COD" | "CVS" | "Other";
    /** @description A list of payment methods for the order. */
    PaymentMethodDetails?: OrdersV0Schema["PaymentMethodDetailItemList"];
    /** @description The identifier for the marketplace where the order was placed. */
    MarketplaceId?: string;
    /**
     * @description The shipment service level category for the order.
     *
     * **Possible values**: `Expedited`, `FreeEconomy`, `NextDay`, `Priority`, `SameDay`, `SecondDay`, `Scheduled`, and `Standard`.
     */
    ShipmentServiceLevelCategory?: string;
    /** @description The status of the Amazon Easy Ship order. This property is only included for Amazon Easy Ship orders. */
    EasyShipShipmentStatus?: OrdersV0Schema["EasyShipShipmentStatus"];
    /** @description Custom ship label for Checkout by Amazon (CBA). */
    CbaDisplayableShippingLabel?: string;
    /**
     * @description The order's type.
     * @enum {string}
     */
    OrderType?:
      | "StandardOrder"
      | "LongLeadTimeOrder"
      | "Preorder"
      | "BackOrder"
      | "SourcingOnDemandOrder";
    /**
     * @description The start of the time period within which you have committed to ship the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders.
     *
     * __Note__: `EarliestShipDate` might not be returned for orders placed before February 1, 2013.
     */
    EarliestShipDate?: string;
    /**
     * @description The end of the time period within which you have committed to ship the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders.
     *
     * __Note__: `LatestShipDate` might not be returned for orders placed before February 1, 2013.
     */
    LatestShipDate?: string;
    /** @description The start of the time period within which you have committed to fulfill the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders. */
    EarliestDeliveryDate?: string;
    /** @description The end of the time period within which you have committed to fulfill the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders that do not have a `PendingAvailability`, `Pending`, or `Canceled` status. */
    LatestDeliveryDate?: string;
    /** @description When true, the order is an Amazon Business order. An Amazon Business order is an order where the buyer is a Verified Business Buyer. */
    IsBusinessOrder?: boolean;
    /** @description When true, the order is a seller-fulfilled Amazon Prime order. */
    IsPrime?: boolean;
    /** @description When true, the order has a Premium Shipping Service Level Agreement. For more information about Premium Shipping orders, refer to "Premium Shipping Options" in the Seller Central Help for your marketplace. */
    IsPremiumOrder?: boolean;
    /** @description When true, the order is a `GlobalExpress` order. */
    IsGlobalExpressEnabled?: boolean;
    /** @description The order ID value for the order that is being replaced. Returned only if IsReplacementOrder = true. */
    ReplacedOrderId?: string;
    /** @description When true, this is a replacement order. */
    IsReplacementOrder?: boolean;
    /** @description Indicates the date by which the seller must respond to the buyer with an estimated ship date. Only returned for Sourcing on Demand orders. */
    PromiseResponseDueDate?: string;
    /** @description When true, the estimated ship date is set for the order. Only returned for Sourcing on Demand orders. */
    IsEstimatedShipDateSet?: boolean;
    /** @description When true, the item within this order was bought and re-sold by Amazon Business EU SARL (ABEU). By buying and instantly re-selling your items, ABEU becomes the seller of record, making your inventory available for sale to customers who would not otherwise purchase from a third-party seller. */
    IsSoldByAB?: boolean;
    /** @description When true, the item within this order was bought and re-sold by Amazon Business EU SARL (ABEU). By buying and instantly re-selling your items, ABEU becomes the seller of record, making your inventory available for sale to customers who would not otherwise purchase from a third-party seller. */
    IsIBA?: boolean;
    /** @description The recommended location for the seller to ship the items from. It is calculated at checkout. The seller may or may not choose to ship from this location. */
    DefaultShipFromLocationAddress?: OrdersV0Schema["Address"];
    /**
     * @description The buyer's invoicing preference. Sellers can use this data to issue electronic invoices for orders in Turkey.
     *
     * **Note**: This attribute is only available in the Turkey marketplace.
     * @enum {string}
     */
    BuyerInvoicePreference?: "INDIVIDUAL" | "BUSINESS";
    /**
     * @description Contains the business invoice tax information. Sellers could use this data to issue electronic invoices for business orders in Turkey.
     *
     * **Note**:
     * 1. This attribute is only available in the Turkey marketplace for the orders that `BuyerInvoicePreference` is BUSINESS.
     * 2. The `BuyerTaxInformation` is a restricted data. Use the Restricted Data Token (RDT) and restricted SPDS roles to access this restricted data.
     */
    BuyerTaxInformation?: OrdersV0Schema["BuyerTaxInformation"];
    /** @description Contains the instructions about the fulfillment, such as the location from where you want the order filled. */
    FulfillmentInstruction?: OrdersV0Schema["FulfillmentInstruction"];
    /** @description When true, this order is marked to be picked up from a store rather than delivered. */
    IsISPU?: boolean;
    /** @description When true, this order is marked to be delivered to an Access Point. The access location is chosen by the customer. Access Points include Amazon Hub Lockers, Amazon Hub Counters, and pickup points operated by carriers. */
    IsAccessPointOrder?: boolean;
    /**
     * @description Tax information about the marketplace where the sale took place. Sellers can use this data to issue electronic invoices for orders in Brazil.
     *
     * **Note**: This attribute is only available in the Brazil marketplace for the orders with `Pending` or `Unshipped` status.
     */
    MarketplaceTaxInfo?: OrdersV0Schema["MarketplaceTaxInfo"];
    /**
     * @description The seller’s friendly name registered in the marketplace where the sale took place. Sellers can use this data to issue electronic invoices for orders in Brazil.
     *
     * **Note**: This attribute is only available in the Brazil marketplace for the orders with `Pending` or `Unshipped` status.
     */
    SellerDisplayName?: string;
    /**
     * @description The shipping address for the order.
     *
     * **Note**:
     * 1. `ShippingAddress` is only available for orders with the following status values: Unshipped, `PartiallyShipped`, Shipped and `InvoiceUnconfirmed`.
     * 2. The `ShippingAddress` contains restricted data. Use the Restricted Data Token (RDT) and restricted SPDS roles to access the restricted data in `ShippingAddress`. For example, `Name`, `AddressLine1`, `AddressLine2`, `AddressLine3`, `Phone`, `AddressType`, and `ExtendedFields`.
     */
    ShippingAddress?: OrdersV0Schema["Address"];
    /**
     * @description Buyer information.
     *
     * **Note**: The `BuyerInfo` contains restricted data. Use the Restricted Data Token (RDT) and restricted SPDS roles to access the restricted data in `BuyerInfo`. For example, `BuyerName`, `BuyerTaxInfo`, and `PurchaseOrderNumber`.
     */
    BuyerInfo?: OrdersV0Schema["BuyerInfo"];
    /** @description Contains information regarding the Shipping Settings Automaton program, such as whether the order's shipping settings were generated automatically, and what those settings are. */
    AutomatedShippingSettings?: OrdersV0Schema["AutomatedShippingSettings"];
    /** @description Whether the order contains regulated items which may require additional approval steps before being fulfilled. */
    HasRegulatedItems?: boolean;
    /** @description The status of the electronic invoice. */
    ElectronicInvoiceStatus?: OrdersV0Schema["ElectronicInvoiceStatus"];
  };
  /** @description Buyer information for an order. */
  OrderBuyerInfo: {
    /** @description An Amazon-defined order identifier, in 3-7-7 format. */
    AmazonOrderId: string;
    /** @description The buyer name or the recipient name. */
    BuyerName?: string;
    /**
     * @description The county of the buyer.
     *
     * **Note**: This attribute is only available in the Brazil marketplace.
     */
    BuyerCounty?: string;
    /**
     * @description Tax information about the buyer. Sellers can use this data to issue electronic invoices for business orders.
     *
     * **Note**: This attribute is only available for business orders in the Brazil, Mexico and India marketplaces.
     */
    BuyerTaxInfo?: OrdersV0Schema["BuyerTaxInfo"];
    /** @description The purchase order (PO) number entered by the buyer at checkout. Only returned for orders where the buyer entered a PO number at checkout. */
    PurchaseOrderNumber?: string;
  };
  /** @description The order's regulated information along with its verification status. */
  OrderRegulatedInfo: {
    /** @description An Amazon-defined order identifier, in 3-7-7 format. */
    AmazonOrderId: string;
    /** @description The regulated information collected during purchase and used to verify the order. */
    RegulatedInformation: OrdersV0Schema["RegulatedInformation"];
    /** @description When true, the order requires attaching a dosage information label when shipped. */
    RequiresDosageLabel: boolean;
    /** @description The order's verification status. */
    RegulatedOrderVerificationStatus: OrdersV0Schema["RegulatedOrderVerificationStatus"];
  };
  /** @description The verification status of the order, along with associated approval or rejection metadata. */
  RegulatedOrderVerificationStatus: {
    /** @description The verification status of the order. */
    Status: OrdersV0Schema["VerificationStatus"];
    /** @description When true, the regulated information provided in the order requires a review by the merchant. */
    RequiresMerchantAction: boolean;
    /** @description A list of valid rejection reasons that may be used to reject the order's regulated information. */
    ValidRejectionReasons: OrdersV0Schema["RejectionReason"][];
    /** @description The reason for rejecting the order's regulated information. Not present if the order isn't rejected. */
    RejectionReason?: OrdersV0Schema["RejectionReason"];
    /** @description The date the order was reviewed. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. */
    ReviewDate?: string;
    /** @description The identifier for the order's regulated information reviewer. */
    ExternalReviewerId?: string;
    /** @description A list of valid verification details that may be provided and the criteria required for when the verification detail can be provided. */
    ValidVerificationDetails?: OrdersV0Schema["ValidVerificationDetail"][];
  };
  /** @description The reason for rejecting the order's regulated information. This is only present if the order is rejected. */
  RejectionReason: {
    /** @description The unique identifier for the rejection reason. */
    RejectionReasonId: string;
    /** @description The description of this rejection reason. */
    RejectionReasonDescription: string;
  };
  /** @description Information about the prescription that is used to verify a regulated product. This must be provided once per order and reflect the seller’s own records. Only approved orders can have prescriptions. */
  PrescriptionDetail: {
    /** @description The identifier for the prescription used to verify the regulated product. */
    prescriptionId: string;
    /**
     * Format: date-time
     * @description The expiration date of the prescription used to verify the regulated product, in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format.
     */
    expirationDate: string;
    /** @description The number of units in each fill as provided in the prescription. */
    writtenQuantity: number;
    /** @description The total number of refills written in the original prescription used to verify the regulated product. If a prescription originally had no refills, this value must be 0. */
    totalRefillsAuthorized: number;
    /** @description The number of refills remaining for the prescription used to verify the regulated product. If a prescription originally had 10 total refills, this value must be `10` for the first order, `9` for the second order, and `0` for the eleventh order. If a prescription originally had no refills, this value must be 0. */
    refillsRemaining: number;
    /** @description The identifier for the clinic which provided the prescription used to verify the regulated product. */
    clinicId: string;
    /** @description The instructions for the prescription as provided by the approver of the regulated product. */
    usageInstructions: string;
  };
  /** @description The types of verification details that may be provided for the order and the criteria required for when the type of verification detail can be provided. The types of verification details allowed depend on the type of regulated product and will not change order to order. */
  ValidVerificationDetail: {
    /** @description A supported type of verification detail. The type indicates which verification detail could be shared while updating the regulated order. Valid value: `prescriptionDetail`. */
    VerificationDetailType: string;
    /** @description A list of valid verification statuses where the associated verification detail type may be provided. For example, if the value of this field is ["Approved"], calls to provide the associated verification detail will fail for orders with a `VerificationStatus` of `Pending`, `Rejected`, `Expired`, or `Cancelled`. */
    ValidVerificationStatuses: OrdersV0Schema["VerificationStatus"][];
  };
  /** @description Additional information related to the verification of a regulated order. */
  VerificationDetails: {
    /** @description Information regarding the prescription tied to the order. */
    prescriptionDetail?: OrdersV0Schema["PrescriptionDetail"];
  };
  /**
   * @description The verification status of the order.
   * @enum {string}
   */
  VerificationStatus:
    | "Pending"
    | "Approved"
    | "Rejected"
    | "Expired"
    | "Cancelled";
  /** @description The regulated information collected during purchase and used to verify the order. */
  RegulatedInformation: {
    /** @description A list of regulated information fields as collected from the regulatory form. */
    Fields: OrdersV0Schema["RegulatedInformationField"][];
  };
  /** @description A field collected from the regulatory form. */
  RegulatedInformationField: {
    /** @description The unique identifier of the field. */
    FieldId: string;
    /** @description The name of the field. */
    FieldLabel: string;
    /**
     * @description The type of field.
     * @enum {string}
     */
    FieldType: "Text" | "FileAttachment";
    /** @description The content of the field as collected in regulatory form. Note that `FileAttachment` type fields contain a URL where you can download the attachment. */
    FieldValue: string;
  };
  /** @description The shipping address for the order. */
  OrderAddress: {
    /** @description An Amazon-defined order identifier, in 3-7-7 format. */
    AmazonOrderId: string;
    /** @description The company name of the contact buyer. For IBA orders, the buyer company must be Amazon entities. */
    BuyerCompanyName?: string;
    /**
     * @description The shipping address for the order.
     *
     * **Note**: `ShippingAddress` is only available for orders with the following status values: `Unshipped`, `PartiallyShipped`, `Shipped`, and `InvoiceUnconfirmed`.
     */
    ShippingAddress?: OrdersV0Schema["Address"];
    DeliveryPreferences?: OrdersV0Schema["DeliveryPreferences"];
  };
  /** @description The shipping address for the order. */
  Address: {
    /** @description The name. */
    Name?: string;
    /**
     * @description The company name of the recipient.
     *
     * **Note**: This attribute is only available for shipping address.
     */
    CompanyName?: string;
    /** @description The street address. */
    AddressLine1?: string;
    /** @description Additional street address information, if required. */
    AddressLine2?: string;
    /** @description Additional street address information, if required. */
    AddressLine3?: string;
    /** @description The city. */
    City?: string;
    /** @description The county. */
    County?: string;
    /** @description The district. */
    District?: string;
    /** @description The state or region. */
    StateOrRegion?: string;
    /** @description The municipality. */
    Municipality?: string;
    /** @description The postal code. */
    PostalCode?: string;
    /** @description The country code. A two-character country code, in ISO 3166-1 alpha-2 format. */
    CountryCode?: string;
    /**
     * @description The phone number of the buyer.
     *
     * **Note**:
     * 1. This attribute is only available for shipping address.
     * 2. In some cases, the buyer phone number is suppressed:
     * a. Phone is suppressed for all `AFN` (fulfilled by Amazon) orders.
     * b. Phone is suppressed for the shipped `MFN` (fulfilled by seller) order when the current date is past the Latest Delivery Date.
     */
    Phone?: string;
    /**
     * @description The container for address extended fields. For example, street name or street number.
     *
     * **Note**: This attribute is currently only available with Brazil shipping addresses.
     */
    ExtendedFields?: OrdersV0Schema["AddressExtendedFields"];
    /**
     * @description The address type of the shipping address.
     * @enum {string}
     */
    AddressType?: "Residential" | "Commercial";
  };
  /** @description The container for address extended fields (such as `street name` and `street number`). Currently only available with Brazil shipping addresses. */
  AddressExtendedFields: {
    /** @description The street name. */
    StreetName?: string;
    /** @description The house, building, or property number associated with the location's street address. */
    StreetNumber?: string;
    /** @description The floor number/unit number in the building/private house number. */
    Complement?: string;
    /** @description The neighborhood. This value is only used in some countries (such as Brazil). */
    Neighborhood?: string;
  };
  /** @description Contains all of the delivery instructions provided by the customer for the shipping address. */
  DeliveryPreferences: {
    /** @description Drop-off location selected by the customer. */
    DropOffLocation?: string;
    /** @description Business hours and days when the delivery is preferred. */
    PreferredDeliveryTime?: OrdersV0Schema["PreferredDeliveryTime"];
    /** @description Enumerated list of miscellaneous delivery attributes associated with the shipping address. */
    OtherAttributes?: OrdersV0Schema["OtherDeliveryAttributes"][];
    /** @description Building instructions, nearby landmark or navigation instructions. */
    AddressInstructions?: string;
  };
  /** @description The time window when the delivery is preferred. */
  PreferredDeliveryTime: {
    /** @description Business hours when the business is open for deliveries. */
    BusinessHours?: OrdersV0Schema["BusinessHours"][];
    /** @description Dates when the business is closed during the next 30 days. */
    ExceptionDates?: OrdersV0Schema["ExceptionDates"][];
  };
  /** @description Business days and hours when the destination is open for deliveries. */
  BusinessHours: {
    /**
     * @description Day of the week.
     * @enum {string}
     */
    DayOfWeek?: "SUN" | "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT";
    /** @description Time window during the day when the business is open. */
    OpenIntervals?: OrdersV0Schema["OpenInterval"][];
  };
  /** @description Dates when the business is closed or open with a different time window. */
  ExceptionDates: {
    /** @description Date when the business is closed, in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date format. */
    ExceptionDate?: string;
    /** @description Boolean indicating if the business is closed or open on that date. */
    IsOpen?: boolean;
    /** @description Time window during the day when the business is open. */
    OpenIntervals?: OrdersV0Schema["OpenInterval"][];
  };
  /** @description The time interval for which the business is open. */
  OpenInterval: {
    /** @description The time when the business opens. */
    StartTime?: OrdersV0Schema["OpenTimeInterval"];
    /** @description The time when the business closes. */
    EndTime?: OrdersV0Schema["OpenTimeInterval"];
  };
  /** @description The time when the business opens or closes. */
  OpenTimeInterval: {
    /** @description The hour when the business opens or closes. */
    Hour?: number;
    /** @description The minute when the business opens or closes. */
    Minute?: number;
  };
  /**
   * @description Miscellaneous delivery attributes associated with the shipping address.
   * @enum {string}
   */
  OtherDeliveryAttributes:
    | "HAS_ACCESS_POINT"
    | "PALLET_ENABLED"
    | "PALLET_DISABLED";
  /** @description The monetary value of the order. */
  Money: {
    /** @description The three-digit currency code. In ISO 4217 format. */
    CurrencyCode?: string;
    /** @description The currency amount. */
    Amount?: string;
  };
  /** @description A list of payment method detail items. */
  PaymentMethodDetailItemList: string[];
  /** @description A list of payment execution detail items. */
  PaymentExecutionDetailItemList: OrdersV0Schema["PaymentExecutionDetailItem"][];
  /** @description Information about a sub-payment method used to pay for a COD order. */
  PaymentExecutionDetailItem: {
    Payment: OrdersV0Schema["Money"];
    /**
     * @description The sub-payment method for an order.
     *
     * **Possible values**:
     * * `COD`: Cash on delivery
     * * `GC`: Gift card
     * * `PointsAccount`: Amazon Points
     * * `Invoice`: Invoice
     * * `CreditCard`: Credit card
     * * `Pix`: Pix
     * * `Other`: Other.
     */
    PaymentMethod: string;
    /**
     * @description The Brazilian Taxpayer Identifier (CNPJ) of the payment processor or acquiring bank that authorizes the payment.
     *
     * **Note**: This attribute is only available for orders in the Brazil (BR) marketplace when the `PaymentMethod` is `CreditCard` or `Pix`.
     */
    AcquirerId?: string;
    /**
     * @description The card network or brand used in the payment transaction (for example, Visa or Mastercard).
     *
     * **Note**: This attribute is only available for orders in the Brazil (BR) marketplace when the `PaymentMethod` is `CreditCard`.
     */
    CardBrand?: string;
    /**
     * @description The unique code that confirms the payment authorization.
     *
     * **Note**: This attribute is only available for orders in the Brazil (BR) marketplace when the `PaymentMethod` is `CreditCard` or `Pix`.
     */
    AuthorizationCode?: string;
  };
  /** @description Tax information about the buyer. */
  BuyerTaxInfo: {
    /** @description The legal name of the company. */
    CompanyLegalName?: string;
    /** @description The country or region imposing the tax. */
    TaxingRegion?: string;
    /** @description A list of tax classifications that apply to the order. */
    TaxClassifications?: OrdersV0Schema["TaxClassification"][];
  };
  /** @description Tax information about the marketplace. */
  MarketplaceTaxInfo: {
    /** @description A list of tax classifications that apply to the order. */
    TaxClassifications?: OrdersV0Schema["TaxClassification"][];
  };
  /** @description The tax classification of the order. */
  TaxClassification: {
    /** @description The type of tax. */
    Name?: string;
    /** @description The buyer's tax identifier. */
    Value?: string;
  };
  /** @description The order items list along with the order ID. */
  OrderItemsList: {
    OrderItems: OrdersV0Schema["OrderItemList"];
    /** @description When present and not empty, pass this string token in the next request to return the next response page. */
    NextToken?: string;
    /** @description An Amazon-defined order identifier, in 3-7-7 format. */
    AmazonOrderId: string;
  };
  /** @description A list of order items. */
  OrderItemList: OrdersV0Schema["OrderItem"][];
  /** @description A single order item. */
  OrderItem: {
    /** @description The item's Amazon Standard Identification Number (ASIN). */
    ASIN: string;
    /** @description The item's seller stock keeping unit (SKU). */
    SellerSKU?: string;
    /** @description An Amazon-defined order item identifier. */
    OrderItemId: string;
    /** @description A list of associated items that a customer has purchased with a product. For example, a tire installation service purchased with tires. */
    AssociatedItems?: OrdersV0Schema["AssociatedItem"][];
    /** @description The item's name. */
    Title?: string;
    /** @description The number of items in the order. */
    QuantityOrdered: number;
    /** @description The number of items shipped. */
    QuantityShipped?: number;
    /** @description The item's product information. */
    ProductInfo?: OrdersV0Schema["ProductInfoDetail"];
    /** @description The number and value of Amazon Points granted with the purchase of an item. */
    PointsGranted?: OrdersV0Schema["PointsGrantedDetail"];
    /** @description The selling price of the order item. Note that an order item is an item and a quantity. This means that the value of `ItemPrice` is equal to the selling price of the item multiplied by the quantity ordered. `ItemPrice` excludes `ShippingPrice` and GiftWrapPrice. */
    ItemPrice?: OrdersV0Schema["Money"];
    /** @description The item's shipping price. */
    ShippingPrice?: OrdersV0Schema["Money"];
    /** @description The tax on the item price. */
    ItemTax?: OrdersV0Schema["Money"];
    /** @description The tax on the shipping price. */
    ShippingTax?: OrdersV0Schema["Money"];
    /** @description The discount on the shipping price. */
    ShippingDiscount?: OrdersV0Schema["Money"];
    /** @description The tax on the discount on the shipping price. */
    ShippingDiscountTax?: OrdersV0Schema["Money"];
    /** @description The total of all promotional discounts in the offer. */
    PromotionDiscount?: OrdersV0Schema["Money"];
    /** @description The tax on the total of all promotional discounts in the offer. */
    PromotionDiscountTax?: OrdersV0Schema["Money"];
    PromotionIds?: OrdersV0Schema["PromotionIdList"];
    /** @description The fee charged for COD service. */
    CODFee?: OrdersV0Schema["Money"];
    /** @description The discount on the COD fee. */
    CODFeeDiscount?: OrdersV0Schema["Money"];
    /**
     * @description Indicates whether the item is a gift.
     *
     * **Possible values**: `true` and `false`.
     */
    IsGift?: string;
    /** @description The condition of the item, as described by the seller. */
    ConditionNote?: string;
    /**
     * @description The condition of the item.
     *
     * **Possible values**: `New`, `Used`, `Collectible`, `Refurbished`, `Preorder`, and `Club`.
     */
    ConditionId?: string;
    /**
     * @description The subcondition of the item.
     *
     * **Possible values**: `New`, `Mint`, `Very Good`, `Good`, `Acceptable`, `Poor`, `Club`, `OEM`, `Warranty`, `Refurbished Warranty`, `Refurbished`, `Open Box`, `Any`, and `Other`.
     */
    ConditionSubtypeId?: string;
    /** @description The start date of the scheduled delivery window in the time zone for the order destination. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. */
    ScheduledDeliveryStartDate?: string;
    /** @description The end date of the scheduled delivery window in the time zone for the order destination. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. */
    ScheduledDeliveryEndDate?: string;
    /**
     * @description Indicates that the selling price is a special price that is only available for Amazon Business orders. For more information about the Amazon Business Seller Program, refer to the [Amazon Business website](https://www.amazon.com/b2b/info/amazon-business).
     *
     * **Possible values**: `BusinessPrice`
     */
    PriceDesignation?: string;
    /** @description Information about withheld taxes. */
    TaxCollection?: OrdersV0Schema["TaxCollection"];
    /**
     * @description When true, the product type for this item has a serial number.
     *
     *  Only returned for Amazon Easy Ship orders.
     */
    SerialNumberRequired?: boolean;
    /**
     * @description When true, the ASIN is enrolled in Transparency. The Transparency serial number that you must submit is determined by:
     *
     * **1D or 2D Barcode:** This has a **T** logo. Submit either the 29-character alpha-numeric identifier beginning with **AZ** or **ZA**, or the 38-character Serialized Global Trade Item Number (SGTIN).
     * **2D Barcode SN:** Submit the 7- to 20-character serial number barcode, which likely has the prefix **SN**. The serial number is applied to the same side of the packaging as the GTIN (UPC/EAN/ISBN) barcode.
     * **QR code SN:** Submit the URL that the QR code generates.
     */
    IsTransparency?: boolean;
    /** @description The IOSS number of the marketplace. Sellers shipping to the EU from outside the EU must provide this IOSS number to their carrier when Amazon has collected the VAT on the sale. */
    IossNumber?: string;
    /** @description The store chain store identifier. Linked to a specific store in a store chain. */
    StoreChainStoreId?: string;
    /**
     * @description The category of deemed reseller. This applies to selling partners that are not based in the EU and is used to help them meet the VAT Deemed Reseller tax laws in the EU and UK.
     * @enum {string}
     */
    DeemedResellerCategory?: "IOSS" | "UOSS";
    /**
     * @description A single item's buyer information.
     *
     * **Note**: The `BuyerInfo` contains restricted data. Use the Restricted Data Token (RDT) and restricted SPDS roles to access the restricted data in `BuyerInfo`. For example, `BuyerCustomizedInfo` and `GiftMessageText`.
     */
    BuyerInfo?: OrdersV0Schema["ItemBuyerInfo"];
    /** @description Information about whether or not a buyer requested cancellation. */
    BuyerRequestedCancel?: OrdersV0Schema["BuyerRequestedCancel"];
    /** @description A list of serial numbers for electronic products that are shipped to customers. Returned for FBA orders only. */
    SerialNumbers?: string[];
    /** @description Substitution preferences for the order item. This is an optional field that is only present if a seller supports substitutions, as is the case with some grocery sellers. */
    SubstitutionPreferences?: OrdersV0Schema["SubstitutionPreferences"];
    /** @description Measurement information for the order item. */
    Measurement?: OrdersV0Schema["Measurement"];
    /** @description Shipping constraints applicable to this order. */
    ShippingConstraints?: OrdersV0Schema["ShippingConstraints"];
    /** @description Contains the list of programs that are associated with an item. */
    AmazonPrograms?: OrdersV0Schema["AmazonPrograms"];
  };
  /**
   * @description Contains the list of programs that Amazon associates with an item.
   *
   * Possible programs are:
   *  - **Subscribe and Save**: Offers recurring, scheduled deliveries to Amazon customers and Amazon Business customers for their frequently ordered products. - **FBM Ship+**: Unlocks expedited shipping without the extra cost. Helps you to provide accurate and fast delivery dates to Amazon customers. You also receive protection from late deliveries, a discount on expedited shipping rates, and cash back when you ship.
   */
  AmazonPrograms: {
    /**
     * @description A list of the programs that Amazon associates with the order item.
     *
     * **Possible values**: `SUBSCRIBE_AND_SAVE`, `FBM_SHIP_PLUS`
     */
    Programs: string[];
  };
  /** @description Substitution preferences for an order item. */
  SubstitutionPreferences: {
    /**
     * @description The type of substitution that these preferences represent.
     * @enum {string}
     */
    SubstitutionType:
      | "CUSTOMER_PREFERENCE"
      | "AMAZON_RECOMMENDED"
      | "DO_NOT_SUBSTITUTE";
    /** @description Substitution options for the order item. */
    SubstitutionOptions?: OrdersV0Schema["SubstitutionOptionList"];
  };
  /** @description A collection of substitution options. */
  SubstitutionOptionList: OrdersV0Schema["SubstitutionOption"][];
  /** @description Substitution options for an order item. */
  SubstitutionOption: {
    /** @description The item's Amazon Standard Identification Number (ASIN). */
    ASIN?: string;
    /** @description The number of items to be picked for this substitution option. */
    QuantityOrdered?: number;
    /** @description The item's seller stock keeping unit (SKU). */
    SellerSKU?: string;
    /** @description The item's title. */
    Title?: string;
    /** @description Measurement information for the substitution option. */
    Measurement?: OrdersV0Schema["Measurement"];
  };
  /** @description Measurement information for an order item. */
  Measurement: {
    /**
     * @description The unit of measure.
     * @enum {string}
     */
    Unit:
      | "OUNCES"
      | "POUNDS"
      | "KILOGRAMS"
      | "GRAMS"
      | "MILLIGRAMS"
      | "INCHES"
      | "FEET"
      | "METERS"
      | "CENTIMETERS"
      | "MILLIMETERS"
      | "SQUARE_METERS"
      | "SQUARE_CENTIMETERS"
      | "SQUARE_FEET"
      | "SQUARE_INCHES"
      | "GALLONS"
      | "PINTS"
      | "QUARTS"
      | "FLUID_OUNCES"
      | "LITERS"
      | "CUBIC_METERS"
      | "CUBIC_FEET"
      | "CUBIC_INCHES"
      | "CUBIC_CENTIMETERS"
      | "COUNT";
    /** @description The measurement value. */
    Value: number;
  };
  /** @description An item that is associated with an order item. For example, a tire installation service that is purchased with tires. */
  AssociatedItem: {
    /** @description The order item's order identifier, in 3-7-7 format. */
    OrderId?: string;
    /** @description An Amazon-defined item identifier for the associated item. */
    OrderItemId?: string;
    AssociationType?: OrdersV0Schema["AssociationType"];
  };
  /**
   * @description The type of association an item has with an order item.
   * @enum {string}
   */
  AssociationType: "VALUE_ADD_SERVICE";
  /** @description A single order item's buyer information list with the order ID. */
  OrderItemsBuyerInfoList: {
    OrderItems: OrdersV0Schema["OrderItemBuyerInfoList"];
    /** @description When present and not empty, pass this string token in the next request to return the next response page. */
    NextToken?: string;
    /** @description An Amazon-defined order identifier, in 3-7-7 format. */
    AmazonOrderId: string;
  };
  /** @description A single order item's buyer information list. */
  OrderItemBuyerInfoList: OrdersV0Schema["OrderItemBuyerInfo"][];
  /** @description A single order item's buyer information. */
  OrderItemBuyerInfo: {
    /** @description An Amazon-defined order item identifier. */
    OrderItemId: string;
    /**
     * @description Buyer information for custom orders from the Amazon Custom program.
     *
     * **Note**: This attribute is only available for MFN (fulfilled by seller) orders.
     */
    BuyerCustomizedInfo?: OrdersV0Schema["BuyerCustomizedInfoDetail"];
    /** @description The gift wrap price of the item. */
    GiftWrapPrice?: OrdersV0Schema["Money"];
    /** @description The tax on the gift wrap price. */
    GiftWrapTax?: OrdersV0Schema["Money"];
    /**
     * @description A gift message provided by the buyer.
     *
     * **Note**: This attribute is only available for MFN (fulfilled by seller) orders.
     */
    GiftMessageText?: string;
    /** @description The gift wrap level specified by the buyer. */
    GiftWrapLevel?: string;
  };
  /** @description The number of Amazon Points offered with the purchase of an item, and their monetary value. */
  PointsGrantedDetail: {
    /** @description The number of Amazon Points granted with the purchase of an item. */
    PointsNumber?: number;
    /** @description The monetary value of the Amazon Points granted. */
    PointsMonetaryValue?: OrdersV0Schema["Money"];
  };
  /** @description Product information on the number of items. */
  ProductInfoDetail: {
    /** @description The total number of items that are included in the ASIN. */
    NumberOfItems?: string;
  };
  /** @description A list of promotion identifiers provided by the seller when the promotions were created. */
  PromotionIdList: string[];
  /** @description Buyer information for custom orders from the Amazon Custom program. */
  BuyerCustomizedInfoDetail: {
    /** @description The location of a ZIP file containing Amazon Custom data. */
    CustomizedURL?: string;
  };
  /** @description Information about withheld taxes. */
  TaxCollection: {
    /**
     * @description The tax collection model applied to the item.
     * @enum {string}
     */
    Model?: "MarketplaceFacilitator";
    /**
     * @description The party responsible for withholding the taxes and remitting them to the taxing authority.
     * @enum {string}
     */
    ResponsibleParty?: "Amazon Services, Inc.";
  };
  /** @description Contains the business invoice tax information. Available only in the TR marketplace. */
  BuyerTaxInformation: {
    /** @description Business buyer's company legal name. */
    BuyerLegalCompanyName?: string;
    /** @description Business buyer's address. */
    BuyerBusinessAddress?: string;
    /** @description Business buyer's tax registration ID. */
    BuyerTaxRegistrationId?: string;
    /** @description Business buyer's tax office. */
    BuyerTaxOffice?: string;
  };
  /** @description Contains the instructions about the fulfillment, such as the location from where you want the order filled. */
  FulfillmentInstruction: {
    /** @description The `sourceId` of the location from where you want the order fulfilled. */
    FulfillmentSupplySourceId?: string;
  };
  /** @description Delivery constraints applicable to this order. */
  ShippingConstraints: {
    /** @description Indicates if the line item needs to be delivered by pallet. */
    PalletDelivery?: OrdersV0Schema["ConstraintType"];
    /** @description Indicates that the recipient of the line item must sign to confirm its delivery. */
    SignatureConfirmation?: OrdersV0Schema["ConstraintType"];
    /** @description Indicates that the person receiving the line item must be the same as the intended recipient of the order. */
    RecipientIdentityVerification?: OrdersV0Schema["ConstraintType"];
    /** @description Indicates that the carrier must confirm the recipient is of the legal age to receive the line item upon delivery. */
    RecipientAgeVerification?: OrdersV0Schema["ConstraintType"];
  };
  /**
   * @description Details the importance of the constraint present on the item
   * @enum {string}
   */
  ConstraintType: "MANDATORY";
  /** @description Buyer information. */
  BuyerInfo: {
    /** @description The buyer name or the recipient name. */
    BuyerName?: string;
    /**
     * @description The county of the buyer.
     *
     * **Note**: This attribute is only available in the Brazil marketplace.
     */
    BuyerCounty?: string;
    /**
     * @description Tax information about the buyer. Sellers could use this data to issue electronic invoices for business orders.
     *
     * **Note**: This attribute is only available for business orders in the Brazil, Mexico and India marketplaces.
     */
    BuyerTaxInfo?: OrdersV0Schema["BuyerTaxInfo"];
    /** @description The purchase order (PO) number entered by the buyer at checkout. Only returned for orders where the buyer entered a PO number at checkout. */
    PurchaseOrderNumber?: string;
  };
  /** @description A single item's buyer information. */
  ItemBuyerInfo: {
    /**
     * @description Buyer information for custom orders from the Amazon Custom program.
     *
     * **Note**: This attribute is only available for MFN (fulfilled by seller) orders.
     */
    BuyerCustomizedInfo?: OrdersV0Schema["BuyerCustomizedInfoDetail"];
    /** @description The gift wrap price of the item. */
    GiftWrapPrice?: OrdersV0Schema["Money"];
    /** @description The tax on the gift wrap price. */
    GiftWrapTax?: OrdersV0Schema["Money"];
    /**
     * @description A gift message provided by the buyer.
     *
     * **Note**: This attribute is only available for MFN (fulfilled by seller) orders.
     */
    GiftMessageText?: string;
    /** @description The gift wrap level specified by the buyer. */
    GiftWrapLevel?: string;
  };
  /** @description Contains information regarding the Shipping Settings Automation program, such as whether the order's shipping settings were generated automatically, and what those settings are. */
  AutomatedShippingSettings: {
    /** @description When true, this order has automated shipping settings generated by Amazon. This order could be identified as an SSA order. */
    HasAutomatedShippingSettings?: boolean;
    /** @description Auto-generated carrier for SSA orders. */
    AutomatedCarrier?: string;
    /** @description Auto-generated ship method for SSA orders. */
    AutomatedShipMethod?: string;
  };
  /** @description Information about whether or not a buyer requested cancellation. */
  BuyerRequestedCancel: {
    /**
     * @description Indicate whether the buyer has requested cancellation.
     *
     * **Possible Values**: `true`, `false`.
     */
    IsBuyerRequestedCancel?: string;
    /** @description The reason that the buyer requested cancellation. */
    BuyerCancelReason?: string;
  };
  /**
   * @description The status of the Amazon Easy Ship order. This property is only included for Amazon Easy Ship orders.
   * @enum {string}
   */
  EasyShipShipmentStatus:
    | "PendingSchedule"
    | "PendingPickUp"
    | "PendingDropOff"
    | "LabelCanceled"
    | "PickedUp"
    | "DroppedOff"
    | "AtOriginFC"
    | "AtDestinationFC"
    | "Delivered"
    | "RejectedByBuyer"
    | "Undeliverable"
    | "ReturningToSeller"
    | "ReturnedToSeller"
    | "Lost"
    | "OutForDelivery"
    | "Damaged";
  /**
   * @description The status of the electronic invoice. Only available for Easy Ship orders and orders in the BR marketplace.
   * @enum {string}
   */
  ElectronicInvoiceStatus:
    | "NotRequired"
    | "NotFound"
    | "Processing"
    | "Errored"
    | "Accepted";
  /** @description The request schema for an shipment confirmation. */
  ConfirmShipmentRequest: {
    packageDetail: OrdersV0Schema["PackageDetail"];
    /**
     * @description The COD collection method (only supported in the JP marketplace).
     * @enum {string}
     */
    codCollectionMethod?: "DirectPayment";
    marketplaceId: OrdersV0Schema["MarketplaceId"];
  };
  /** @description The error response schema for the `confirmShipment` operation. */
  ConfirmShipmentErrorResponse: {
    /** @description One or more unexpected errors occurred during the `confirmShipment` operation. */
    errors?: OrdersV0Schema["ErrorList"];
  };
  /** @description Properties of packages */
  PackageDetail: {
    packageReferenceId: OrdersV0Schema["PackageReferenceId"];
    /** @description Identifies the carrier that will deliver the package. This field is required for all marketplaces. For more information, refer to the [`CarrierCode` announcement](https://developer-docs.amazon.com/sp-api/changelog/carriercode-value-required-in-shipment-confirmations-for-br-mx-ca-sg-au-in-jp-marketplaces). */
    carrierCode: string;
    /** @description Carrier name that will deliver the package. Required when `carrierCode` is "Other" */
    carrierName?: string;
    /** @description Ship method to be used for shipping the order. */
    shippingMethod?: string;
    /** @description The tracking number used to obtain tracking and delivery information. */
    trackingNumber: string;
    /**
     * Format: date-time
     * @description The shipping date for the package. Must be in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date/time format.
     */
    shipDate: string;
    /** @description The unique identifier for the supply source. */
    shipFromSupplySourceId?: string;
    /** @description The list of order items and quantities to be updated. */
    orderItems: OrdersV0Schema["ConfirmShipmentOrderItemsList"];
  };
  /** @description A list of order items. */
  ConfirmShipmentOrderItemsList: OrdersV0Schema["ConfirmShipmentOrderItem"][];
  /** @description A single order item. */
  ConfirmShipmentOrderItem: {
    /** @description The order item's unique identifier. */
    orderItemId: string;
    /** @description The item's quantity. */
    quantity: number;
    /** @description The list of transparency codes. */
    transparencyCodes?: OrdersV0Schema["TransparencyCodeList"];
  };
  /** @description A list of order items. */
  TransparencyCodeList: OrdersV0Schema["TransparencyCode"][];
  /** @description The transparency code associated with the item. */
  TransparencyCode: string;
  /** @description A seller-supplied identifier that uniquely identifies a package within the scope of an order. Only positive numeric values are supported. */
  PackageReferenceId: string;
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: OrdersV0Schema["Error"][];
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition. */
    message: string;
    /** @description Additional details that can help the caller understand or fix the issue. */
    details?: string;
  };
}

export interface operations {
  /**
   * Returns orders that are created or updated during the specified time period. If you want to return specific types of orders, you can apply filters to your request. `NextToken` doesn't affect any filters that you include in your request; it only impacts the pagination for the filtered orders response.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.0167 | 20 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrders: {
    parameters: {
      query: {
        /**
         * Use this date to select orders created after (or at) a specified time. Only orders placed after the specified time are returned. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: Either the `CreatedAfter` parameter or the `LastUpdatedAfter` parameter is required. Both cannot be empty. `LastUpdatedAfter` and `LastUpdatedBefore` cannot be set when `CreatedAfter` is set.
         */
        CreatedAfter?: string;
        /**
         * Use this date to select orders created before (or at) a specified time. Only orders placed before the specified time are returned. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: `CreatedBefore` is optional when `CreatedAfter` is set. If specified, `CreatedBefore` must be equal to or after the `CreatedAfter` date and at least two minutes before current time.
         */
        CreatedBefore?: string;
        /**
         * Use this date to select orders that were last updated after (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: Either the `CreatedAfter` parameter or the `LastUpdatedAfter` parameter is required. Both cannot be empty. `CreatedAfter` or `CreatedBefore` cannot be set when `LastUpdatedAfter` is set.
         */
        LastUpdatedAfter?: string;
        /**
         * Use this date to select orders that were last updated before (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
         *
         * **Note**: `LastUpdatedBefore` is optional when `LastUpdatedAfter` is set. But if specified, `LastUpdatedBefore` must be equal to or after the `LastUpdatedAfter` date and at least two minutes before current time.
         */
        LastUpdatedBefore?: string;
        /**
         * A list of `OrderStatus` values used to filter the results.
         *
         * **Possible values:**
         * - `PendingAvailability` (This status is available for pre-orders only. The order has been placed, payment has not been authorized, and the release date of the item is in the future.)
         * - `Pending` (The order has been placed but payment has not been authorized.)
         * - `Unshipped` (Payment has been authorized and the order is ready for shipment, but no items in the order have been shipped.)
         * - `PartiallyShipped` (One or more, but not all, items in the order have been shipped.)
         * - `Shipped` (All items in the order have been shipped.)
         * - `InvoiceUnconfirmed` (All items in the order have been shipped. The seller has not yet given confirmation to Amazon that the invoice has been shipped to the buyer.)
         * - `Canceled` (The order has been canceled.)
         * - `Unfulfillable` (The order cannot be fulfilled. This state applies only to Multi-Channel Fulfillment orders.)
         */
        OrderStatuses?: string[];
        /**
         * A list of `MarketplaceId` values. Used to select orders that were placed in the specified marketplaces.
         *
         * Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) for a complete list of `marketplaceId` values.
         */
        MarketplaceIds: string[];
        /**
         * A list that indicates how an order was fulfilled. Filters the results by fulfillment channel.
         *
         * **Possible values**: `AFN` (fulfilled by Amazon), `MFN` (fulfilled by seller).
         */
        FulfillmentChannels?: string[];
        /**
         * A list of payment method values. Use this field to select orders that were paid with the specified payment methods.
         *
         * **Possible values**: `COD` (cash on delivery), `CVS` (convenience store), `Other` (Any payment method other than COD or CVS).
         */
        PaymentMethods?: string[];
        /** An order identifier that is specified by the seller. Used to select only the orders that match the order identifier. If `SellerOrderId` is specified, then `FulfillmentChannels`, `OrderStatuses`, `PaymentMethod`, `LastUpdatedAfter`, and `LastUpdatedBefore` cannot be specified. */
        SellerOrderId?: string;
        /** A number that indicates the maximum number of orders that can be returned per page. Value must be 1 - 100. Default 100. */
        MaxResultsPerPage?: number;
        /**
         * A list of `EasyShipShipmentStatus` values. Used to select Easy Ship orders with statuses that match the specified values. If `EasyShipShipmentStatus` is specified, only Amazon Easy Ship orders are returned.
         *
         * **Possible values:**
         * - `PendingSchedule` (The package is awaiting the schedule for pick-up.)
         * - `PendingPickUp` (Amazon has not yet picked up the package from the seller.)
         * - `PendingDropOff` (The seller will deliver the package to the carrier.)
         * - `LabelCanceled` (The seller canceled the pickup.)
         * - `PickedUp` (Amazon has picked up the package from the seller.)
         * - `DroppedOff` (The package is delivered to the carrier by the seller.)
         * - `AtOriginFC` (The packaged is at the origin fulfillment center.)
         * - `AtDestinationFC` (The package is at the destination fulfillment center.)
         * - `Delivered` (The package has been delivered.)
         * - `RejectedByBuyer` (The package has been rejected by the buyer.)
         * - `Undeliverable` (The package cannot be delivered.)
         * - `ReturningToSeller` (The package was not delivered and is being returned to the seller.)
         * - `ReturnedToSeller` (The package was not delivered and was returned to the seller.)
         * - `Lost` (The package is lost.)
         * - `OutForDelivery` (The package is out for delivery.)
         * - `Damaged` (The package was damaged by the carrier.)
         */
        EasyShipShipmentStatuses?: string[];
        /**
         * A list of `ElectronicInvoiceStatus` values. Used to select orders with electronic invoice statuses that match the specified values.
         *
         * **Possible values:**
         * - `NotRequired` (Electronic invoice submission is not required for this order.)
         * - `NotFound` (The electronic invoice was not submitted for this order.)
         * - `Processing` (The electronic invoice is being processed for this order.)
         * - `Errored` (The last submitted electronic invoice was rejected for this order.)
         * - `Accepted` (The last submitted electronic invoice was submitted and accepted.)
         */
        ElectronicInvoiceStatuses?: string[];
        /** A string token returned in the response of your previous request. */
        NextToken?: string;
        /** A list of `AmazonOrderId` values. An `AmazonOrderId` is an Amazon-defined order identifier, in 3-7-7 format. */
        AmazonOrderIds?: string[];
        /** The `sourceId` of the location from where you want the order fulfilled. */
        ActualFulfillmentSupplySourceId?: string;
        /** When true, this order is marked to be picked up from a store rather than delivered. */
        IsISPU?: boolean;
        /** The store chain store identifier. Linked to a specific store in a store chain. */
        StoreChainStoreId?: string;
        /** Use this date to select orders with an earliest delivery date before (or at) a specified time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. */
        EarliestDeliveryDateBefore?: string;
        /** Use this date to select orders with an earliest delivery date after (or at) a specified time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. */
        EarliestDeliveryDateAfter?: string;
        /** Use this date to select orders with a latest delivery date before (or at) a specified time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. */
        LatestDeliveryDateBefore?: string;
        /** Use this date to select orders with a latest delivery date after (or at) a specified time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. */
        LatestDeliveryDateAfter?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrdersResponse"];
      };
    };
  };
  /**
   * Returns the order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrder: {
    parameters: {
      path: {
        /** An Amazon-defined order identifier, in 3-7-7 format. */
        orderId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrderResponse"];
      };
    };
  };
  /**
   * Returns buyer information for the order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrderBuyerInfo: {
    parameters: {
      path: {
        /** The Amazon order identifier in 3-7-7 format. */
        orderId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrderBuyerInfoResponse"];
      };
    };
  };
  /**
   * Returns the shipping address for the order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrderAddress: {
    parameters: {
      path: {
        /** The Amazon order identifier in 3-7-7 format. */
        orderId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrderAddressResponse"];
      };
    };
  };
  /**
   * Returns detailed order item information for the order that you specify. If `NextToken` is provided, it's used to retrieve the next page of order items.
   *
   * __Note__: When an order is in the Pending state (the order has been placed but payment has not been authorized), the getOrderItems operation does not return information about pricing, taxes, shipping charges, gift status or promotions for the order items in the order. After an order leaves the Pending state (this occurs when payment has been authorized) and enters the Unshipped, Partially Shipped, or Shipped state, the getOrderItems operation returns information about pricing, taxes, shipping charges, gift status and promotions for the order items in the order.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrderItems: {
    parameters: {
      path: {
        /** An Amazon-defined order identifier, in 3-7-7 format. */
        orderId: string;
      };
      query: {
        /** A string token returned in the response of your previous request. */
        NextToken?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsResponse"];
      };
    };
  };
  /**
   * Returns buyer information for the order items in the order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrderItemsBuyerInfo: {
    parameters: {
      path: {
        /** An Amazon-defined order identifier, in 3-7-7 format. */
        orderId: string;
      };
      query: {
        /** A string token returned in the response of your previous request. */
        NextToken?: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrderItemsBuyerInfoResponse"];
      };
    };
  };
  /**
   * Update the shipment status for an order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 5 | 15 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  updateShipmentStatus: {
    parameters: {
      path: {
        /** An Amazon-defined order identifier, in 3-7-7 format. */
        orderId: string;
      };
      body: {
        /** The request body for the `updateShipmentStatus` operation. */
        payload: OrdersV0Schema["UpdateShipmentStatusRequest"];
      };
    };
    responses: {
      /** Success. */
      204: never;
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["UpdateShipmentStatusErrorResponse"];
      };
    };
  };
  /**
   * Returns regulated information for the order that you specify.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getOrderRegulatedInfo: {
    parameters: {
      path: {
        /** The Amazon order identifier in 3-7-7 format. */
        orderId: string;
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
      /** Indicates access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["GetOrderRegulatedInfoResponse"];
      };
    };
  };
  /**
   * Updates (approves or rejects) the verification status of an order containing regulated products.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  updateVerificationStatus: {
    parameters: {
      path: {
        /** The Amazon order identifier in 3-7-7 format. */
        orderId: string;
      };
      body: {
        /** The request body for the `updateVerificationStatus` operation. */
        payload: OrdersV0Schema["UpdateVerificationStatusRequest"];
      };
    };
    responses: {
      /** Success. */
      204: never;
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["UpdateVerificationStatusErrorResponse"];
      };
    };
  };
  /**
   * Updates the shipment confirmation status for a specified order.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 2 | 10 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  confirmShipment: {
    parameters: {
      path: {
        /** An Amazon-defined order identifier, in 3-7-7 format. */
        orderId: string;
      };
      body: {
        /** Request body of `confirmShipment`. */
        payload: OrdersV0Schema["ConfirmShipmentRequest"];
      };
    };
    responses: {
      /** Success. */
      204: never;
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
      /** The request's Authorization header is not formatted correctly or does not contain a valid token. */
      401: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
      /** The specified resource does not exist. */
      404: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: OrdersV0Schema["ConfirmShipmentErrorResponse"];
      };
    };
  };
}

export interface external {}

export default OrdersV0Schema;
