/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sellers/v1/marketplaceParticipations": {
    /**
     * Returns a list of marketplaces where the seller can list items and information about the seller's participation in those marketplaces.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.016 | 15 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getMarketplaceParticipations"];
  };
  "/sellers/v1/account": {
    /**
     * Returns information about a seller account and its marketplaces.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.016 | 15 |
     *
     * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getAccount"];
  };
}

export interface SellersSchema {
  /** @description Error response returned when the request is unsuccessful. */
  Error: {
    /** @description An error code that identifies the type of error that occurred. */
    code: string;
    /** @description A message that describes the error condition in a human-readable form. */
    message: string;
    /** @description Additional details that can help you understand or fix the issue. */
    details?: string;
  };
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: SellersSchema["Error"][];
  MarketplaceParticipation: {
    marketplace: SellersSchema["Marketplace"];
    participation: SellersSchema["Participation"];
    /** @description The name of the seller's store as displayed in the marketplace. */
    storeName: string;
  };
  /** @description List of marketplace participations. */
  MarketplaceParticipationList: SellersSchema["MarketplaceParticipation"][];
  /** @description The response schema for the `getMarketplaceParticipations` operation. */
  GetMarketplaceParticipationsResponse: {
    /** @description The payload for the `getMarketplaceParticipations` operation. */
    payload?: SellersSchema["MarketplaceParticipationList"];
    /** @description The errors encountered by the `getMarketplaceParticipations` operation. */
    errors?: SellersSchema["ErrorList"];
  };
  /** @description Information about an Amazon marketplace where a seller can list items and customers can view and purchase items. */
  Marketplace: {
    /** @description The encrypted marketplace value. */
    id: string;
    /** @description The marketplace name. */
    name: string;
    /** @description The ISO 3166-1 alpha-2 format country code of the marketplace. */
    countryCode: string;
    /** @description The ISO 4217 format currency code of the marketplace. */
    defaultCurrencyCode: string;
    /** @description The ISO 639-1 format language code of the marketplace. */
    defaultLanguageCode: string;
    /** @description The domain name of the marketplace. */
    domainName: string;
  };
  /** @description Information that is specific to a seller in a marketplace. */
  Participation: {
    /** @description If `true`, the seller participates in the marketplace. Otherwise `false`. */
    isParticipating: boolean;
    /** @description Specifies if the seller has suspended listings. `true` if the seller Listing Status is set to Inactive, otherwise `false`. */
    hasSuspendedListings: boolean;
  };
  /** @description The response schema for the `getAccount` operation. */
  GetAccountResponse: {
    payload?: SellersSchema["Account"];
    /** @description The errors encountered by the `getAccount` operation. */
    errors?: SellersSchema["ErrorList"];
  };
  /** @description The response schema for the `getAccount` operation. */
  Account: {
    marketplaceParticipationList: SellersSchema["MarketplaceParticipationList"];
    /**
     * @description The type of business registered for the seller account.
     * @enum {string}
     */
    businessType:
      | "CHARITY"
      | "CRAFTSMAN"
      | "NATURAL_PERSON_COMPANY"
      | "PUBLIC_LISTED"
      | "PRIVATE_LIMITED"
      | "SOLE_PROPRIETORSHIP"
      | "STATE_OWNED"
      | "INDIVIDUAL";
    /**
     * @description The selling plan details.
     * @enum {string}
     */
    sellingPlan: "PROFESSIONAL" | "INDIVIDUAL";
    business?: SellersSchema["Business"];
    primaryContact?: SellersSchema["PrimaryContact"];
  };
  /** @description Information about the seller's business. Certain fields may be omitted depending on the seller's `businessType`. */
  Business: {
    /** @description The registered business name. */
    name: string;
    /** @description The registered business address. */
    registeredBusinessAddress: SellersSchema["Address"];
    /** @description The seller's company registration number, if applicable. This field will be absent for individual sellers and sole proprietorships. */
    companyRegistrationNumber?: string;
    /** @description The seller's company tax identification number, if applicable. This field will be present for certain business types only, such as sole proprietorships. */
    companyTaxIdentificationNumber?: string;
    /** @description The non-Latin script version of the registered business name, if applicable. */
    nonLatinName?: string;
  };
  /** @description Represents an address */
  Address: {
    /** @description Street address information. */
    addressLine1: string;
    /** @description Additional street address information. */
    addressLine2?: string;
    /** @description The country code in two-character ISO 3166-1 alpha-2 format. */
    countryCode: string;
    /** @description The state or province code. */
    stateOrProvinceCode?: string;
    /** @description The city. */
    city?: string;
    /** @description The postal code. */
    postalCode?: string;
  };
  /** @description Information about the seller's primary contact. */
  PrimaryContact: {
    /** @description The full name of the seller's primary contact. */
    name: string;
    /** @description The primary contact's residential address. */
    address: SellersSchema["Address"];
    /** @description The non-Latin script version of the primary contact's name, if applicable. */
    nonLatinName?: string;
  };
}

export interface operations {
  /**
   * Returns a list of marketplaces where the seller can list items and information about the seller's participation in those marketplaces.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.016 | 15 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getMarketplaceParticipations: {
    parameters: {};
    responses: {
      /** Marketplace participations successfully retrieved. */
      200: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** 403 can be caused for reasons like Access Denied, Unauthorized, Expired Token, Invalid Signature or Resource Not Found. */
      403: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** The entity of the request is in a format not supported by the requested resource. */
      415: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** Encountered an unexpected condition which prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: SellersSchema["GetMarketplaceParticipationsResponse"];
      };
    };
  };
  /**
   * Returns information about a seller account and its marketplaces.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.016 | 15 |
   *
   * The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getAccount: {
    parameters: {};
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: SellersSchema["GetAccountResponse"];
      };
    };
  };
}

export interface external {}

export default SellersSchema;
