/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/finances/transfers/2024-06-01/payouts": {
    /**
     * Initiates an on-demand payout to the seller's default deposit method in Seller Central for the given `marketplaceId` and `accountType`, if eligible. You can only initiate one on-demand payout for each marketplace and account type within a 24-hour period.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | 0.017 | 2 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    post: operations["initiatePayout"];
  };
  "/finances/transfers/2024-06-01/paymentMethods": {
    /**
     * Returns the list of payment methods for the seller, which can be filtered by method type.
     *
     * **Usage Plan:**
     *
     * | Rate (requests per second) | Burst |
     * | ---- | ---- |
     * | .5 | 30 |
     *
     * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     */
    get: operations["getPaymentMethods"];
  };
}

export interface TransfersSchema {
  /**
   * @description The request schema for the `initiatePayout` operation.
   * @example {
   *   "marketplaceId": "APJ6JRA9NG5V4",
   *   "accountType": "Standard Orders"
   * }
   */
  InitiatePayoutRequest: {
    /** @description The identifier of the Amazon marketplace. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE. For a list of possible marketplace IDs, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
    marketplaceId: TransfersSchema["MarketplaceId"];
    /** @description The account type in the selected marketplace for which a payout must be initiated. For supported EU marketplaces, the only account type is `Standard Orders`. */
    accountType: string;
  };
  /**
   * @description The response schema for the `initiatePayout` operation.
   * @example {
   *   "payoutReferenceId": "3DM7DQi8DPAMOLOSaN5HxT0q2waNwH95fopx3AD2Lgc"
   * }
   */
  InitiatePayoutResponse: {
    /** @description The financial event group ID for a successfully initiated payout. You can use this ID to track payout information. */
    payoutReferenceId: string;
  };
  /**
   * @description The response schema for the `getPaymentMethods` operation.
   * @example {
   *   "paymentMethods": [
   *     {
   *       "accountHolderName": "John Doe",
   *       "paymentMethodId": "0h_TU_CUS_4058fe2a-da6b-4b82-8e48-b20ff2eb4f6d",
   *       "paymentMethodType": "BANK_ACCOUNT",
   *       "tail": "677",
   *       "assignmentType": "DEFAULT_DEPOSIT_METHOD"
   *     },
   *     {
   *       "countryCode": "US",
   *       "accountHolderName": "John Doe",
   *       "paymentMethodId": "0h_TU_CUS_4058fe2a-da6b-4b82-8e48-b20ff2eb4f6d",
   *       "paymentMethodType": "CARD",
   *       "expiryDate": {
   *         "month": "3",
   *         "year": "2029"
   *       },
   *       "tail": "677"
   *     }
   *   ]
   * }
   */
  GetPaymentMethodsResponse: {
    paymentMethods?: TransfersSchema["PaymentMethodList"];
  };
  /** @description The list of payment methods with payment method details. */
  PaymentMethodList: TransfersSchema["PaymentMethodDetails"][];
  /** @description The details of a payment method. */
  PaymentMethodDetails: {
    /** @description The name of the account holder who is registered for the payment method. */
    accountHolderName?: string;
    /**
     * @description The payment method identifier.
     * @example 0h_TU_CUS_4058fe2a-da6b-4b82-8e48-b20ff2eb4f6d
     */
    paymentMethodId?: string;
    /**
     * @description The last three or four digits of the payment method.
     * @example 321
     */
    tail?: string;
    /** @description The expiration date of the card used for payment. */
    expiryDate?: TransfersSchema["ExpiryDate"];
    /**
     * @description The two-letter country code in ISO 3166-1 alpha-2 format. For payment methods in the `card` category, the code is for the country where the card was issued. For payment methods in the `bank account` category, the code is for the country where the account is located.
     * @example US
     */
    countryCode?: string;
    /** @description The payment method type. */
    paymentMethodType?: TransfersSchema["PaymentMethodType"];
    /** @description The payment method assignment type, whether it is assigned as default to the given marketplace or not. */
    assignmentType?: TransfersSchema["AssignmentType"];
  };
  /** @description The expiration date of the card used for payment. If the payment method is not `card`, the expiration date is `null`. */
  ExpiryDate: {
    /**
     * @description The month the card expires expressed as a number from `1` to `12`.
     * @example 3
     */
    month?: string;
    /**
     * @description Year
     * @example 2024
     */
    year?: string;
  };
  /**
   * @description The list of payment method types that are present.
   * @example [
   *   "BANK_ACCOUNT, CARD"
   * ]
   */
  PaymentMethodTypeList: TransfersSchema["PaymentMethodType"][];
  /**
   * @description The type of payment method.
   * @enum {string}
   */
  PaymentMethodType: "BANK_ACCOUNT" | "CARD" | "SELLER_WALLET";
  /**
   * @description The default payment method type.
   * @enum {string}
   */
  AssignmentType: "DEFAULT_DEPOSIT_METHOD";
  /**
   * @description The identifier of the Amazon marketplace. For the list of all marketplace IDs, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
   * @example A1PA6795UKMFR9
   */
  MarketplaceId: string;
  /** @description A list of error responses returned when a request is unsuccessful. */
  ErrorList: {
    /**
     * @description array of errors
     * @example [
     *   {
     *     "code": "InvalidInput",
     *     "message": "The input request had one or more invalid input parameters."
     *   }
     * ]
     */
    errors: TransfersSchema["Error"][];
  };
  /**
   * @description Error response returned when the request is unsuccessful.
   * @example {
   *   "code": "InvalidInput",
   *   "message": "The input request had one or more invalid input parameters."
   * }
   */
  Error: {
    /**
     * @description An error code that identifies the type of error that occurred.
     * @example InvalidInput
     */
    code: string;
    /**
     * @description A message that describes the error condition.
     * @example The input request had one or more invalid input parameters.
     */
    message: string;
    /**
     * @description Additional details that can help the caller understand or fix the issue.
     * @example The following input parameters are invalid : [ marketplaceId ].
     */
    details?: string;
  };
}

export interface operations {
  /**
   * Initiates an on-demand payout to the seller's default deposit method in Seller Central for the given `marketplaceId` and `accountType`, if eligible. You can only initiate one on-demand payout for each marketplace and account type within a 24-hour period.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | 0.017 | 2 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  initiatePayout: {
    parameters: {
      body: {
        /** The request body for the `initiatePayout` operation. */
        body: TransfersSchema["InitiatePayoutRequest"];
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: TransfersSchema["InitiatePayoutResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
    };
  };
  /**
   * Returns the list of payment methods for the seller, which can be filtered by method type.
   *
   * **Usage Plan:**
   *
   * | Rate (requests per second) | Burst |
   * | ---- | ---- |
   * | .5 | 30 |
   *
   * The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
   */
  getPaymentMethods: {
    parameters: {
      query: {
        /** The identifier of the marketplace from which you want to retrieve payment methods. For the list of possible marketplace identifiers, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids). */
        marketplaceId: string;
        /** A comma-separated list of the payment method types you want to include in the response. */
        paymentMethodTypes?: ("BANK_ACCOUNT" | "CARD" | "SELLER_WALLET")[];
      };
    };
    responses: {
      /** Success. */
      200: {
        headers: {};
        schema: TransfersSchema["GetPaymentMethodsResponse"];
      };
      /** Request has missing or invalid parameters and cannot be parsed. */
      400: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature. */
      403: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The resource specified does not exist. */
      404: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The request size exceeded the maximum accepted size. */
      413: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The request payload is in an unsupported format. */
      415: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** The frequency of requests was greater than allowed. */
      429: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** An unexpected condition occurred that prevented the server from fulfilling the request. */
      500: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
      /** Temporary overloading or maintenance of the server. */
      503: {
        headers: {};
        schema: TransfersSchema["ErrorList"];
      };
    };
  };
}

export interface external {}

export default TransfersSchema;
